#ifndef MAGICWAND_MODEL_FUNCTIONS_H
#define MAGICWAND_MODEL_FUNCTIONS_H

typedef ap_fixed<32,13> fix1_t;

#define BATCH 128
#define DATA_SIZE 3
#define FIRST_NUM_ROWS 4
#define FIRST_NUM_COLS 3
#define FIRST_NUM_KERNELS 8
#define SECOND_NUM_ROWS 4
#define SECOND_NUM_COLS 8
#define SECOND_NUM_KERNELS 16
#define THIRD_NUM_ROWS 14
#define THIRD_NUM_COLS 16
#define THIRD_NUM_KERNELS 16
#define FOURTH_NUM_SIZE 16
#define FOURTH_NUM_KERNELS 4

#endif //MAGICWAND_MODEL_FUNCTIONS_H
