// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module master_fix_dense1_fix_Pipeline_Dense1_Loop218 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_0_address0,
        m_0_ce0,
        m_0_q0,
        m_0_address1,
        m_0_ce1,
        m_0_q1,
        num_V_992_out,
        num_V_992_out_ap_vld,
        grp_fu_1868_p_din0,
        grp_fu_1868_p_din1,
        grp_fu_1868_p_dout0,
        grp_fu_1868_p_ce,
        grp_fu_1872_p_din0,
        grp_fu_1872_p_din1,
        grp_fu_1872_p_dout0,
        grp_fu_1872_p_ce,
        grp_fu_1876_p_din0,
        grp_fu_1876_p_din1,
        grp_fu_1876_p_dout0,
        grp_fu_1876_p_ce,
        grp_fu_1880_p_din0,
        grp_fu_1880_p_din1,
        grp_fu_1880_p_dout0,
        grp_fu_1880_p_ce,
        grp_fu_1896_p_din0,
        grp_fu_1896_p_din1,
        grp_fu_1896_p_dout0,
        grp_fu_1896_p_ce,
        grp_fu_1884_p_din0,
        grp_fu_1884_p_din1,
        grp_fu_1884_p_dout0,
        grp_fu_1884_p_ce,
        grp_fu_1888_p_din0,
        grp_fu_1888_p_din1,
        grp_fu_1888_p_dout0,
        grp_fu_1888_p_ce,
        grp_fu_1916_p_din0,
        grp_fu_1916_p_din1,
        grp_fu_1916_p_dout0,
        grp_fu_1916_p_ce,
        grp_fu_1892_p_din0,
        grp_fu_1892_p_din1,
        grp_fu_1892_p_dout0,
        grp_fu_1892_p_ce,
        grp_fu_1900_p_din0,
        grp_fu_1900_p_din1,
        grp_fu_1900_p_dout0,
        grp_fu_1900_p_ce,
        grp_fu_1904_p_din0,
        grp_fu_1904_p_din1,
        grp_fu_1904_p_dout0,
        grp_fu_1904_p_ce,
        grp_fu_1972_p_din0,
        grp_fu_1972_p_din1,
        grp_fu_1972_p_dout0,
        grp_fu_1972_p_ce,
        grp_fu_2004_p_din0,
        grp_fu_2004_p_din1,
        grp_fu_2004_p_dout0,
        grp_fu_2004_p_ce,
        grp_fu_2008_p_din0,
        grp_fu_2008_p_din1,
        grp_fu_2008_p_dout0,
        grp_fu_2008_p_ce,
        grp_fu_2012_p_din0,
        grp_fu_2012_p_din1,
        grp_fu_2012_p_dout0,
        grp_fu_2012_p_ce,
        grp_fu_1912_p_din0,
        grp_fu_1912_p_din1,
        grp_fu_1912_p_dout0,
        grp_fu_1912_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 15'd1;
parameter    ap_ST_fsm_pp0_stage1 = 15'd2;
parameter    ap_ST_fsm_pp0_stage2 = 15'd4;
parameter    ap_ST_fsm_pp0_stage3 = 15'd8;
parameter    ap_ST_fsm_pp0_stage4 = 15'd16;
parameter    ap_ST_fsm_pp0_stage5 = 15'd32;
parameter    ap_ST_fsm_pp0_stage6 = 15'd64;
parameter    ap_ST_fsm_pp0_stage7 = 15'd128;
parameter    ap_ST_fsm_pp0_stage8 = 15'd256;
parameter    ap_ST_fsm_pp0_stage9 = 15'd512;
parameter    ap_ST_fsm_pp0_stage10 = 15'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 15'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 15'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 15'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] m_0_address0;
output   m_0_ce0;
input  [34:0] m_0_q0;
output  [7:0] m_0_address1;
output   m_0_ce1;
input  [34:0] m_0_q1;
output  [35:0] num_V_992_out;
output   num_V_992_out_ap_vld;
output  [19:0] grp_fu_1868_p_din0;
output  [34:0] grp_fu_1868_p_din1;
input  [53:0] grp_fu_1868_p_dout0;
output   grp_fu_1868_p_ce;
output  [17:0] grp_fu_1872_p_din0;
output  [34:0] grp_fu_1872_p_din1;
input  [52:0] grp_fu_1872_p_dout0;
output   grp_fu_1872_p_ce;
output  [18:0] grp_fu_1876_p_din0;
output  [34:0] grp_fu_1876_p_din1;
input  [53:0] grp_fu_1876_p_dout0;
output   grp_fu_1876_p_ce;
output  [18:0] grp_fu_1880_p_din0;
output  [34:0] grp_fu_1880_p_din1;
input  [53:0] grp_fu_1880_p_dout0;
output   grp_fu_1880_p_ce;
output  [19:0] grp_fu_1896_p_din0;
output  [34:0] grp_fu_1896_p_din1;
input  [54:0] grp_fu_1896_p_dout0;
output   grp_fu_1896_p_ce;
output  [18:0] grp_fu_1884_p_din0;
output  [34:0] grp_fu_1884_p_din1;
input  [53:0] grp_fu_1884_p_dout0;
output   grp_fu_1884_p_ce;
output  [18:0] grp_fu_1888_p_din0;
output  [34:0] grp_fu_1888_p_din1;
input  [53:0] grp_fu_1888_p_dout0;
output   grp_fu_1888_p_ce;
output  [18:0] grp_fu_1916_p_din0;
output  [34:0] grp_fu_1916_p_din1;
input  [53:0] grp_fu_1916_p_dout0;
output   grp_fu_1916_p_ce;
output  [17:0] grp_fu_1892_p_din0;
output  [34:0] grp_fu_1892_p_din1;
input  [52:0] grp_fu_1892_p_dout0;
output   grp_fu_1892_p_ce;
output  [17:0] grp_fu_1900_p_din0;
output  [34:0] grp_fu_1900_p_din1;
input  [52:0] grp_fu_1900_p_dout0;
output   grp_fu_1900_p_ce;
output  [19:0] grp_fu_1904_p_din0;
output  [34:0] grp_fu_1904_p_din1;
input  [54:0] grp_fu_1904_p_dout0;
output   grp_fu_1904_p_ce;
output  [18:0] grp_fu_1972_p_din0;
output  [34:0] grp_fu_1972_p_din1;
input  [53:0] grp_fu_1972_p_dout0;
output   grp_fu_1972_p_ce;
output  [18:0] grp_fu_2004_p_din0;
output  [34:0] grp_fu_2004_p_din1;
input  [53:0] grp_fu_2004_p_dout0;
output   grp_fu_2004_p_ce;
output  [18:0] grp_fu_2008_p_din0;
output  [34:0] grp_fu_2008_p_din1;
input  [53:0] grp_fu_2008_p_dout0;
output   grp_fu_2008_p_ce;
output  [18:0] grp_fu_2012_p_din0;
output  [34:0] grp_fu_2012_p_din1;
input  [53:0] grp_fu_2012_p_dout0;
output   grp_fu_2012_p_ce;
output  [19:0] grp_fu_1912_p_din0;
output  [34:0] grp_fu_1912_p_din1;
input  [54:0] grp_fu_1912_p_dout0;
output   grp_fu_1912_p_ce;

reg ap_idle;
reg[7:0] m_0_address0;
reg m_0_ce0;
reg[7:0] m_0_address1;
reg m_0_ce1;
reg num_V_992_out_ap_vld;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state20_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln285_reg_2128;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_state15_pp0_stage14_iter0;
wire    ap_block_pp0_stage14_subdone;
wire   [3:0] firstDense_f_V_14_0_address0;
reg    firstDense_f_V_14_0_ce0;
wire   [18:0] firstDense_f_V_14_0_q0;
wire   [3:0] firstDense_f_V_14_1_address0;
reg    firstDense_f_V_14_1_ce0;
wire   [17:0] firstDense_f_V_14_1_q0;
wire   [3:0] firstDense_f_V_14_2_address0;
reg    firstDense_f_V_14_2_ce0;
wire   [18:0] firstDense_f_V_14_2_q0;
wire   [3:0] firstDense_f_V_14_3_address0;
reg    firstDense_f_V_14_3_ce0;
wire   [18:0] firstDense_f_V_14_3_q0;
wire   [3:0] firstDense_f_V_14_4_address0;
reg    firstDense_f_V_14_4_ce0;
wire   [19:0] firstDense_f_V_14_4_q0;
wire   [3:0] firstDense_f_V_14_5_address0;
reg    firstDense_f_V_14_5_ce0;
wire   [18:0] firstDense_f_V_14_5_q0;
wire   [3:0] firstDense_f_V_14_6_address0;
reg    firstDense_f_V_14_6_ce0;
wire   [18:0] firstDense_f_V_14_6_q0;
wire   [3:0] firstDense_f_V_14_7_address0;
reg    firstDense_f_V_14_7_ce0;
wire   [18:0] firstDense_f_V_14_7_q0;
wire   [3:0] firstDense_f_V_14_8_address0;
reg    firstDense_f_V_14_8_ce0;
wire   [17:0] firstDense_f_V_14_8_q0;
wire   [3:0] firstDense_f_V_14_9_address0;
reg    firstDense_f_V_14_9_ce0;
wire   [17:0] firstDense_f_V_14_9_q0;
wire   [3:0] firstDense_f_V_14_10_address0;
reg    firstDense_f_V_14_10_ce0;
wire   [19:0] firstDense_f_V_14_10_q0;
wire   [3:0] firstDense_f_V_14_11_address0;
reg    firstDense_f_V_14_11_ce0;
wire   [18:0] firstDense_f_V_14_11_q0;
wire   [3:0] firstDense_f_V_14_12_address0;
reg    firstDense_f_V_14_12_ce0;
wire   [18:0] firstDense_f_V_14_12_q0;
wire   [3:0] firstDense_f_V_14_13_address0;
reg    firstDense_f_V_14_13_ce0;
wire   [18:0] firstDense_f_V_14_13_q0;
wire   [3:0] firstDense_f_V_14_14_address0;
reg    firstDense_f_V_14_14_ce0;
wire   [18:0] firstDense_f_V_14_14_q0;
wire   [3:0] firstDense_f_V_14_15_address0;
reg    firstDense_f_V_14_15_ce0;
wire   [19:0] firstDense_f_V_14_15_q0;
reg   [34:0] reg_482;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state17_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state18_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state19_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
wire    ap_block_pp0_stage8_11001;
reg   [34:0] reg_486;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state16_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln285_fu_503_p2;
wire   [7:0] tmp_s_fu_535_p3;
reg   [7:0] tmp_s_reg_2132;
reg   [18:0] aux2_V_reg_2250;
reg   [17:0] aux2_V_93_reg_2255;
reg   [18:0] aux2_V_94_reg_2260;
reg   [18:0] aux2_V_95_reg_2265;
reg   [19:0] aux2_V_96_reg_2270;
reg   [18:0] aux2_V_97_reg_2275;
reg   [18:0] aux2_V_98_reg_2280;
reg   [18:0] aux2_V_99_reg_2285;
reg   [17:0] aux2_V_100_reg_2290;
reg   [17:0] aux2_V_101_reg_2295;
reg   [19:0] aux2_V_102_reg_2300;
reg   [18:0] aux2_V_103_reg_2305;
reg   [18:0] aux2_V_104_reg_2310;
reg   [18:0] aux2_V_105_reg_2315;
reg   [18:0] aux2_V_106_reg_2320;
reg   [19:0] aux2_V_107_reg_2325;
wire   [53:0] zext_ln1168_fu_624_p1;
wire  signed [53:0] sext_ln1171_fu_628_p1;
wire   [52:0] zext_ln1168_63_fu_637_p1;
wire  signed [52:0] sext_ln1171_76_fu_641_p1;
reg  signed [53:0] r_V_reg_2370;
wire   [17:0] trunc_ln727_fu_678_p1;
reg   [17:0] trunc_ln727_reg_2376;
reg  signed [52:0] r_V_308_reg_2381;
wire   [17:0] trunc_ln727_104_fu_682_p1;
reg   [17:0] trunc_ln727_104_reg_2387;
wire   [53:0] zext_ln1168_64_fu_686_p1;
wire  signed [53:0] sext_ln1171_77_fu_690_p1;
wire   [53:0] zext_ln1168_65_fu_699_p1;
wire  signed [53:0] sext_ln1171_78_fu_703_p1;
wire   [35:0] num_V_188_fu_806_p2;
reg   [35:0] num_V_188_reg_2422;
wire   [0:0] r_93_fu_812_p2;
reg   [0:0] r_93_reg_2427;
reg  signed [53:0] r_V_309_reg_2432;
wire   [17:0] trunc_ln727_105_fu_817_p1;
reg   [17:0] trunc_ln727_105_reg_2438;
reg  signed [53:0] r_V_310_reg_2443;
wire   [17:0] trunc_ln727_106_fu_821_p1;
reg   [17:0] trunc_ln727_106_reg_2449;
wire   [54:0] zext_ln1168_66_fu_825_p1;
wire  signed [54:0] sext_ln1171_79_fu_829_p1;
wire   [53:0] zext_ln1168_67_fu_838_p1;
wire  signed [53:0] sext_ln1171_80_fu_842_p1;
wire   [35:0] num_V_190_fu_935_p2;
reg   [35:0] num_V_190_reg_2484;
wire   [0:0] r_94_fu_941_p2;
reg   [0:0] r_94_reg_2489;
wire   [0:0] r_95_fu_946_p2;
reg   [0:0] r_95_reg_2494;
reg   [54:0] r_V_311_reg_2499;
wire   [17:0] trunc_ln727_107_fu_951_p1;
reg   [17:0] trunc_ln727_107_reg_2504;
reg  signed [53:0] r_V_312_reg_2509;
wire   [17:0] trunc_ln727_108_fu_955_p1;
reg   [17:0] trunc_ln727_108_reg_2515;
wire   [53:0] zext_ln1168_68_fu_959_p1;
wire  signed [53:0] sext_ln1171_81_fu_963_p1;
wire   [53:0] zext_ln1168_69_fu_972_p1;
wire  signed [53:0] sext_ln1171_82_fu_976_p1;
wire   [35:0] num_V_192_fu_1069_p2;
reg   [35:0] num_V_192_reg_2550;
wire   [0:0] r_96_fu_1075_p2;
reg   [0:0] r_96_reg_2555;
wire   [0:0] r_97_fu_1080_p2;
reg   [0:0] r_97_reg_2560;
reg  signed [53:0] r_V_313_reg_2565;
wire   [17:0] trunc_ln727_109_fu_1085_p1;
reg   [17:0] trunc_ln727_109_reg_2571;
reg  signed [53:0] r_V_314_reg_2576;
wire   [17:0] trunc_ln727_110_fu_1089_p1;
reg   [17:0] trunc_ln727_110_reg_2582;
wire   [52:0] zext_ln1168_70_fu_1093_p1;
wire  signed [52:0] sext_ln1171_83_fu_1097_p1;
wire   [52:0] zext_ln1168_71_fu_1106_p1;
wire  signed [52:0] sext_ln1171_84_fu_1110_p1;
wire   [35:0] num_V_194_fu_1203_p2;
reg   [35:0] num_V_194_reg_2617;
wire   [0:0] r_98_fu_1209_p2;
reg   [0:0] r_98_reg_2622;
wire   [0:0] r_99_fu_1214_p2;
reg   [0:0] r_99_reg_2627;
reg  signed [52:0] r_V_315_reg_2632;
wire   [17:0] trunc_ln727_111_fu_1219_p1;
reg   [17:0] trunc_ln727_111_reg_2638;
reg  signed [52:0] r_V_316_reg_2643;
wire   [17:0] trunc_ln727_112_fu_1223_p1;
reg   [17:0] trunc_ln727_112_reg_2649;
wire   [54:0] zext_ln1168_72_fu_1227_p1;
wire  signed [54:0] sext_ln1171_85_fu_1231_p1;
wire   [53:0] zext_ln1168_73_fu_1240_p1;
wire  signed [53:0] sext_ln1171_86_fu_1244_p1;
wire   [35:0] num_V_196_fu_1306_p2;
reg   [35:0] num_V_196_reg_2674;
wire   [0:0] r_100_fu_1312_p2;
reg   [0:0] r_100_reg_2679;
wire   [0:0] r_101_fu_1317_p2;
reg   [0:0] r_101_reg_2684;
reg   [54:0] r_V_317_reg_2689;
wire   [17:0] trunc_ln727_113_fu_1322_p1;
reg   [17:0] trunc_ln727_113_reg_2694;
reg  signed [53:0] r_V_318_reg_2699;
wire   [17:0] trunc_ln727_114_fu_1326_p1;
reg   [17:0] trunc_ln727_114_reg_2705;
wire   [53:0] zext_ln1168_74_fu_1330_p1;
wire  signed [53:0] sext_ln1171_87_fu_1334_p1;
wire   [53:0] zext_ln1168_75_fu_1343_p1;
wire  signed [53:0] sext_ln1171_88_fu_1347_p1;
wire   [35:0] num_V_198_fu_1412_p2;
reg   [35:0] num_V_198_reg_2730;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state10_pp0_stage9_iter0;
wire    ap_block_pp0_stage9_11001;
wire   [0:0] r_102_fu_1418_p2;
reg   [0:0] r_102_reg_2735;
wire   [0:0] r_103_fu_1423_p2;
reg   [0:0] r_103_reg_2740;
reg  signed [53:0] r_V_319_reg_2745;
wire   [17:0] trunc_ln727_115_fu_1428_p1;
reg   [17:0] trunc_ln727_115_reg_2751;
reg  signed [53:0] r_V_320_reg_2756;
wire   [17:0] trunc_ln727_116_fu_1432_p1;
reg   [17:0] trunc_ln727_116_reg_2762;
wire   [53:0] zext_ln1168_76_fu_1436_p1;
wire  signed [53:0] sext_ln1171_89_fu_1440_p1;
wire   [54:0] zext_ln1168_77_fu_1449_p1;
wire  signed [54:0] sext_ln1171_90_fu_1453_p1;
wire   [35:0] num_V_200_fu_1518_p2;
reg   [35:0] num_V_200_reg_2787;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state11_pp0_stage10_iter0;
wire    ap_block_pp0_stage10_11001;
wire   [0:0] r_104_fu_1524_p2;
reg   [0:0] r_104_reg_2792;
wire   [0:0] r_105_fu_1529_p2;
reg   [0:0] r_105_reg_2797;
reg  signed [53:0] r_V_321_reg_2802;
wire   [17:0] trunc_ln727_117_fu_1534_p1;
reg   [17:0] trunc_ln727_117_reg_2808;
reg   [54:0] r_V_322_reg_2813;
wire   [17:0] trunc_ln727_118_fu_1538_p1;
reg   [17:0] trunc_ln727_118_reg_2818;
wire   [35:0] num_V_202_fu_1598_p2;
reg   [35:0] num_V_202_reg_2823;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_state12_pp0_stage11_iter0;
wire    ap_block_pp0_stage11_11001;
wire   [0:0] r_106_fu_1604_p2;
reg   [0:0] r_106_reg_2828;
wire   [0:0] r_107_fu_1609_p2;
reg   [0:0] r_107_reg_2833;
wire   [35:0] num_V_204_fu_1670_p2;
reg   [35:0] num_V_204_reg_2838;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_state13_pp0_stage12_iter0;
wire    ap_block_pp0_stage12_11001;
wire   [35:0] num_V_206_fu_1732_p2;
reg   [35:0] num_V_206_reg_2843;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_state14_pp0_stage13_iter0;
wire    ap_block_pp0_stage13_11001;
wire   [35:0] num_V_208_fu_1791_p2;
reg   [35:0] num_V_208_reg_2848;
wire    ap_block_pp0_stage14_11001;
wire   [35:0] num_V_210_fu_1853_p2;
reg   [35:0] num_V_210_reg_2853;
wire   [35:0] num_V_212_fu_1915_p2;
reg   [35:0] num_V_212_reg_2858;
wire   [35:0] num_V_214_fu_1977_p2;
reg   [35:0] num_V_214_reg_2863;
wire   [35:0] num_V_216_fu_2039_p2;
reg   [35:0] num_V_216_reg_2868;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln289_fu_543_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_89_fu_554_p3;
wire   [63:0] i_18_cast_fu_515_p1;
wire   [63:0] tmp_90_fu_573_p3;
wire    ap_block_pp0_stage1;
wire   [63:0] tmp_91_fu_587_p3;
wire   [63:0] tmp_92_fu_601_p3;
wire    ap_block_pp0_stage2;
wire   [63:0] tmp_93_fu_615_p3;
wire   [63:0] tmp_94_fu_655_p3;
wire    ap_block_pp0_stage3;
wire   [63:0] tmp_95_fu_669_p3;
wire   [63:0] tmp_96_fu_720_p3;
wire    ap_block_pp0_stage4;
wire   [63:0] tmp_97_fu_734_p3;
wire   [63:0] tmp_98_fu_856_p3;
wire    ap_block_pp0_stage5;
wire   [63:0] tmp_99_fu_870_p3;
wire   [63:0] tmp_100_fu_990_p3;
wire    ap_block_pp0_stage6;
wire   [63:0] tmp_101_fu_1004_p3;
wire   [63:0] tmp_102_fu_1124_p3;
wire    ap_block_pp0_stage7;
wire   [63:0] tmp_103_fu_1138_p3;
reg   [35:0] lhs_fu_122;
wire   [35:0] num_V_fu_2098_p2;
reg   [35:0] ap_sig_allocacmp_lhs_load_7;
wire    ap_loop_init;
reg   [3:0] i_fu_126;
reg   [3:0] ap_sig_allocacmp_i_8;
wire   [3:0] add_ln285_fu_509_p2;
wire    ap_block_pp0_stage4_01001;
wire   [7:0] or_ln289_fu_548_p2;
wire   [7:0] or_ln289_58_fu_568_p2;
wire   [7:0] or_ln289_59_fu_582_p2;
wire   [7:0] or_ln289_60_fu_596_p2;
wire   [7:0] or_ln289_61_fu_610_p2;
wire   [7:0] or_ln289_62_fu_650_p2;
wire   [7:0] or_ln289_63_fu_664_p2;
wire   [7:0] or_ln289_64_fu_715_p2;
wire   [7:0] or_ln289_65_fu_729_p2;
wire   [54:0] lhs_188_fu_743_p3;
wire  signed [54:0] sext_ln1245_fu_751_p1;
wire   [54:0] ret_V_fu_754_p2;
wire   [0:0] p_Result_s_fu_770_p3;
wire   [0:0] r_fu_785_p2;
wire   [0:0] or_ln412_fu_790_p2;
wire   [0:0] p_Result_315_fu_778_p3;
wire   [0:0] and_ln412_fu_796_p2;
wire   [35:0] num_V_187_fu_760_p4;
wire   [35:0] zext_ln415_fu_802_p1;
wire   [7:0] or_ln289_66_fu_851_p2;
wire   [7:0] or_ln289_67_fu_865_p2;
wire   [54:0] lhs_190_fu_879_p3;
wire  signed [54:0] sext_ln1245_52_fu_886_p1;
wire   [54:0] ret_V_91_fu_889_p2;
wire   [0:0] p_Result_286_fu_905_p3;
wire   [0:0] or_ln412_76_fu_920_p2;
wire   [0:0] p_Result_316_fu_913_p3;
wire   [0:0] and_ln412_77_fu_925_p2;
wire   [35:0] num_V_189_fu_895_p4;
wire   [35:0] zext_ln415_76_fu_931_p1;
wire   [7:0] or_ln289_68_fu_985_p2;
wire   [7:0] or_ln289_69_fu_999_p2;
wire   [54:0] lhs_192_fu_1013_p3;
wire  signed [54:0] sext_ln1245_53_fu_1020_p1;
wire   [54:0] ret_V_92_fu_1023_p2;
wire   [0:0] p_Result_288_fu_1039_p3;
wire   [0:0] or_ln412_77_fu_1054_p2;
wire   [0:0] p_Result_317_fu_1047_p3;
wire   [0:0] and_ln412_78_fu_1059_p2;
wire   [35:0] num_V_191_fu_1029_p4;
wire   [35:0] zext_ln415_77_fu_1065_p1;
wire   [7:0] or_ln289_70_fu_1119_p2;
wire   [7:0] or_ln289_71_fu_1133_p2;
wire   [54:0] lhs_194_fu_1147_p3;
wire  signed [54:0] sext_ln1245_54_fu_1154_p1;
wire   [54:0] ret_V_93_fu_1157_p2;
wire   [0:0] p_Result_290_fu_1173_p3;
wire   [0:0] or_ln412_78_fu_1188_p2;
wire   [0:0] p_Result_318_fu_1181_p3;
wire   [0:0] and_ln412_79_fu_1193_p2;
wire   [35:0] num_V_193_fu_1163_p4;
wire   [35:0] zext_ln415_78_fu_1199_p1;
wire    ap_block_pp0_stage8;
wire   [54:0] lhs_196_fu_1253_p3;
wire   [54:0] ret_V_94_fu_1260_p2;
wire   [0:0] p_Result_292_fu_1275_p3;
wire   [0:0] or_ln412_79_fu_1291_p2;
wire   [0:0] p_Result_319_fu_1283_p3;
wire   [0:0] and_ln412_80_fu_1296_p2;
wire   [35:0] num_V_195_fu_1265_p4;
wire   [35:0] zext_ln415_79_fu_1302_p1;
wire    ap_block_pp0_stage9;
wire   [54:0] lhs_198_fu_1356_p3;
wire  signed [54:0] sext_ln1245_55_fu_1363_p1;
wire   [54:0] ret_V_95_fu_1366_p2;
wire   [0:0] p_Result_294_fu_1382_p3;
wire   [0:0] or_ln412_80_fu_1397_p2;
wire   [0:0] p_Result_320_fu_1390_p3;
wire   [0:0] and_ln412_81_fu_1402_p2;
wire   [35:0] num_V_197_fu_1372_p4;
wire   [35:0] zext_ln415_80_fu_1408_p1;
wire    ap_block_pp0_stage10;
wire   [54:0] lhs_200_fu_1462_p3;
wire  signed [54:0] sext_ln1245_56_fu_1469_p1;
wire   [54:0] ret_V_96_fu_1472_p2;
wire   [0:0] p_Result_296_fu_1488_p3;
wire   [0:0] or_ln412_81_fu_1503_p2;
wire   [0:0] p_Result_321_fu_1496_p3;
wire   [0:0] and_ln412_82_fu_1508_p2;
wire   [35:0] num_V_199_fu_1478_p4;
wire   [35:0] zext_ln415_81_fu_1514_p1;
wire    ap_block_pp0_stage11;
wire   [54:0] lhs_202_fu_1542_p3;
wire  signed [54:0] sext_ln1245_57_fu_1549_p1;
wire   [54:0] ret_V_97_fu_1552_p2;
wire   [0:0] p_Result_298_fu_1568_p3;
wire   [0:0] or_ln412_82_fu_1583_p2;
wire   [0:0] p_Result_322_fu_1576_p3;
wire   [0:0] and_ln412_83_fu_1588_p2;
wire   [35:0] num_V_201_fu_1558_p4;
wire   [35:0] zext_ln415_82_fu_1594_p1;
wire    ap_block_pp0_stage12;
wire   [54:0] lhs_204_fu_1614_p3;
wire  signed [54:0] sext_ln1245_58_fu_1621_p1;
wire   [54:0] ret_V_98_fu_1624_p2;
wire   [0:0] p_Result_300_fu_1640_p3;
wire   [0:0] or_ln412_83_fu_1655_p2;
wire   [0:0] p_Result_323_fu_1648_p3;
wire   [0:0] and_ln412_84_fu_1660_p2;
wire   [35:0] num_V_203_fu_1630_p4;
wire   [35:0] zext_ln415_83_fu_1666_p1;
wire    ap_block_pp0_stage13;
wire   [54:0] lhs_206_fu_1676_p3;
wire  signed [54:0] sext_ln1245_59_fu_1683_p1;
wire   [54:0] ret_V_99_fu_1686_p2;
wire   [0:0] p_Result_302_fu_1702_p3;
wire   [0:0] or_ln412_84_fu_1717_p2;
wire   [0:0] p_Result_324_fu_1710_p3;
wire   [0:0] and_ln412_85_fu_1722_p2;
wire   [35:0] num_V_205_fu_1692_p4;
wire   [35:0] zext_ln415_84_fu_1728_p1;
wire    ap_block_pp0_stage14;
wire   [54:0] lhs_208_fu_1738_p3;
wire   [54:0] ret_V_100_fu_1745_p2;
wire   [0:0] p_Result_304_fu_1760_p3;
wire   [0:0] or_ln412_85_fu_1776_p2;
wire   [0:0] p_Result_325_fu_1768_p3;
wire   [0:0] and_ln412_86_fu_1781_p2;
wire   [35:0] num_V_207_fu_1750_p4;
wire   [35:0] zext_ln415_85_fu_1787_p1;
wire   [54:0] lhs_210_fu_1797_p3;
wire  signed [54:0] sext_ln1245_60_fu_1804_p1;
wire   [54:0] ret_V_101_fu_1807_p2;
wire   [0:0] p_Result_306_fu_1823_p3;
wire   [0:0] or_ln412_86_fu_1838_p2;
wire   [0:0] p_Result_326_fu_1831_p3;
wire   [0:0] and_ln412_87_fu_1843_p2;
wire   [35:0] num_V_209_fu_1813_p4;
wire   [35:0] zext_ln415_86_fu_1849_p1;
wire   [54:0] lhs_212_fu_1859_p3;
wire  signed [54:0] sext_ln1245_61_fu_1866_p1;
wire   [54:0] ret_V_102_fu_1869_p2;
wire   [0:0] p_Result_308_fu_1885_p3;
wire   [0:0] or_ln412_87_fu_1900_p2;
wire   [0:0] p_Result_327_fu_1893_p3;
wire   [0:0] and_ln412_88_fu_1905_p2;
wire   [35:0] num_V_211_fu_1875_p4;
wire   [35:0] zext_ln415_87_fu_1911_p1;
wire   [54:0] lhs_214_fu_1921_p3;
wire  signed [54:0] sext_ln1245_62_fu_1928_p1;
wire   [54:0] ret_V_103_fu_1931_p2;
wire   [0:0] p_Result_310_fu_1947_p3;
wire   [0:0] or_ln412_88_fu_1962_p2;
wire   [0:0] p_Result_328_fu_1955_p3;
wire   [0:0] and_ln412_89_fu_1967_p2;
wire   [35:0] num_V_213_fu_1937_p4;
wire   [35:0] zext_ln415_88_fu_1973_p1;
wire   [54:0] lhs_216_fu_1983_p3;
wire  signed [54:0] sext_ln1245_63_fu_1990_p1;
wire   [54:0] ret_V_104_fu_1993_p2;
wire   [0:0] p_Result_312_fu_2009_p3;
wire   [0:0] or_ln412_89_fu_2024_p2;
wire   [0:0] p_Result_329_fu_2017_p3;
wire   [0:0] and_ln412_90_fu_2029_p2;
wire   [35:0] num_V_215_fu_1999_p4;
wire   [35:0] zext_ln415_89_fu_2035_p1;
wire   [54:0] lhs_218_fu_2045_p3;
wire   [54:0] ret_V_105_fu_2052_p2;
wire   [0:0] p_Result_314_fu_2067_p3;
wire   [0:0] or_ln412_90_fu_2083_p2;
wire   [0:0] p_Result_330_fu_2075_p3;
wire   [0:0] and_ln412_91_fu_2088_p2;
wire   [35:0] num_V_217_fu_2057_p4;
wire   [35:0] zext_ln415_90_fu_2094_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [14:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_0 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_0_address0),
    .ce0(firstDense_f_V_14_0_ce0),
    .q0(firstDense_f_V_14_0_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_1 #(
    .DataWidth( 18 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_1_address0),
    .ce0(firstDense_f_V_14_1_ce0),
    .q0(firstDense_f_V_14_1_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_2 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_2_address0),
    .ce0(firstDense_f_V_14_2_ce0),
    .q0(firstDense_f_V_14_2_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_3 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_3_address0),
    .ce0(firstDense_f_V_14_3_ce0),
    .q0(firstDense_f_V_14_3_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_4 #(
    .DataWidth( 20 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_4_address0),
    .ce0(firstDense_f_V_14_4_ce0),
    .q0(firstDense_f_V_14_4_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_5 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_5_address0),
    .ce0(firstDense_f_V_14_5_ce0),
    .q0(firstDense_f_V_14_5_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_6 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_6_address0),
    .ce0(firstDense_f_V_14_6_ce0),
    .q0(firstDense_f_V_14_6_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_7 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_7_address0),
    .ce0(firstDense_f_V_14_7_ce0),
    .q0(firstDense_f_V_14_7_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_8 #(
    .DataWidth( 18 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_8_address0),
    .ce0(firstDense_f_V_14_8_ce0),
    .q0(firstDense_f_V_14_8_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_9 #(
    .DataWidth( 18 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_9_address0),
    .ce0(firstDense_f_V_14_9_ce0),
    .q0(firstDense_f_V_14_9_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_10 #(
    .DataWidth( 20 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_10_address0),
    .ce0(firstDense_f_V_14_10_ce0),
    .q0(firstDense_f_V_14_10_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_11 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_11_address0),
    .ce0(firstDense_f_V_14_11_ce0),
    .q0(firstDense_f_V_14_11_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_12 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_12_address0),
    .ce0(firstDense_f_V_14_12_ce0),
    .q0(firstDense_f_V_14_12_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_13 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_13_address0),
    .ce0(firstDense_f_V_14_13_ce0),
    .q0(firstDense_f_V_14_13_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_14 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_14_address0),
    .ce0(firstDense_f_V_14_14_ce0),
    .q0(firstDense_f_V_14_14_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop218_firstDense_f_V_14_15 #(
    .DataWidth( 20 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_14_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_14_15_address0),
    .ce0(firstDense_f_V_14_15_ce0),
    .q0(firstDense_f_V_14_15_q0)
);

master_fix_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage14_subdone) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln285_fu_503_p2 == 1'd0))) begin
            i_fu_126 <= add_ln285_fu_509_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_126 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lhs_fu_122 <= 36'd68719441644;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        lhs_fu_122 <= num_V_fu_2098_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        aux2_V_100_reg_2290 <= firstDense_f_V_14_8_q0;
        aux2_V_101_reg_2295 <= firstDense_f_V_14_9_q0;
        aux2_V_102_reg_2300 <= firstDense_f_V_14_10_q0;
        aux2_V_103_reg_2305 <= firstDense_f_V_14_11_q0;
        aux2_V_104_reg_2310 <= firstDense_f_V_14_12_q0;
        aux2_V_105_reg_2315 <= firstDense_f_V_14_13_q0;
        aux2_V_106_reg_2320 <= firstDense_f_V_14_14_q0;
        aux2_V_107_reg_2325 <= firstDense_f_V_14_15_q0;
        aux2_V_93_reg_2255 <= firstDense_f_V_14_1_q0;
        aux2_V_94_reg_2260 <= firstDense_f_V_14_2_q0;
        aux2_V_95_reg_2265 <= firstDense_f_V_14_3_q0;
        aux2_V_96_reg_2270 <= firstDense_f_V_14_4_q0;
        aux2_V_97_reg_2275 <= firstDense_f_V_14_5_q0;
        aux2_V_98_reg_2280 <= firstDense_f_V_14_6_q0;
        aux2_V_99_reg_2285 <= firstDense_f_V_14_7_q0;
        aux2_V_reg_2250 <= firstDense_f_V_14_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln285_reg_2128 <= icmp_ln285_fu_503_p2;
        num_V_210_reg_2853 <= num_V_210_fu_1853_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        num_V_188_reg_2422 <= num_V_188_fu_806_p2;
        r_93_reg_2427 <= r_93_fu_812_p2;
        r_V_309_reg_2432 <= grp_fu_1876_p_dout0;
        r_V_310_reg_2443 <= grp_fu_1880_p_dout0;
        trunc_ln727_105_reg_2438 <= trunc_ln727_105_fu_817_p1;
        trunc_ln727_106_reg_2449 <= trunc_ln727_106_fu_821_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        num_V_190_reg_2484 <= num_V_190_fu_935_p2;
        r_94_reg_2489 <= r_94_fu_941_p2;
        r_95_reg_2494 <= r_95_fu_946_p2;
        r_V_311_reg_2499 <= grp_fu_1896_p_dout0;
        r_V_312_reg_2509 <= grp_fu_1884_p_dout0;
        trunc_ln727_107_reg_2504 <= trunc_ln727_107_fu_951_p1;
        trunc_ln727_108_reg_2515 <= trunc_ln727_108_fu_955_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        num_V_192_reg_2550 <= num_V_192_fu_1069_p2;
        r_96_reg_2555 <= r_96_fu_1075_p2;
        r_97_reg_2560 <= r_97_fu_1080_p2;
        r_V_313_reg_2565 <= grp_fu_1888_p_dout0;
        r_V_314_reg_2576 <= grp_fu_1916_p_dout0;
        trunc_ln727_109_reg_2571 <= trunc_ln727_109_fu_1085_p1;
        trunc_ln727_110_reg_2582 <= trunc_ln727_110_fu_1089_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        num_V_194_reg_2617 <= num_V_194_fu_1203_p2;
        r_98_reg_2622 <= r_98_fu_1209_p2;
        r_99_reg_2627 <= r_99_fu_1214_p2;
        r_V_315_reg_2632 <= grp_fu_1892_p_dout0;
        r_V_316_reg_2643 <= grp_fu_1900_p_dout0;
        trunc_ln727_111_reg_2638 <= trunc_ln727_111_fu_1219_p1;
        trunc_ln727_112_reg_2649 <= trunc_ln727_112_fu_1223_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        num_V_196_reg_2674 <= num_V_196_fu_1306_p2;
        r_100_reg_2679 <= r_100_fu_1312_p2;
        r_101_reg_2684 <= r_101_fu_1317_p2;
        r_V_317_reg_2689 <= grp_fu_1904_p_dout0;
        r_V_318_reg_2699 <= grp_fu_1972_p_dout0;
        trunc_ln727_113_reg_2694 <= trunc_ln727_113_fu_1322_p1;
        trunc_ln727_114_reg_2705 <= trunc_ln727_114_fu_1326_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        num_V_198_reg_2730 <= num_V_198_fu_1412_p2;
        r_102_reg_2735 <= r_102_fu_1418_p2;
        r_103_reg_2740 <= r_103_fu_1423_p2;
        r_V_319_reg_2745 <= grp_fu_2004_p_dout0;
        r_V_320_reg_2756 <= grp_fu_2008_p_dout0;
        trunc_ln727_115_reg_2751 <= trunc_ln727_115_fu_1428_p1;
        trunc_ln727_116_reg_2762 <= trunc_ln727_116_fu_1432_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        num_V_200_reg_2787 <= num_V_200_fu_1518_p2;
        r_104_reg_2792 <= r_104_fu_1524_p2;
        r_105_reg_2797 <= r_105_fu_1529_p2;
        r_V_321_reg_2802 <= grp_fu_2012_p_dout0;
        r_V_322_reg_2813 <= grp_fu_1912_p_dout0;
        trunc_ln727_117_reg_2808 <= trunc_ln727_117_fu_1534_p1;
        trunc_ln727_118_reg_2818 <= trunc_ln727_118_fu_1538_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        num_V_202_reg_2823 <= num_V_202_fu_1598_p2;
        r_106_reg_2828 <= r_106_fu_1604_p2;
        r_107_reg_2833 <= r_107_fu_1609_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        num_V_204_reg_2838 <= num_V_204_fu_1670_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        num_V_206_reg_2843 <= num_V_206_fu_1732_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        num_V_208_reg_2848 <= num_V_208_fu_1791_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        num_V_212_reg_2858 <= num_V_212_fu_1915_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        num_V_214_reg_2863 <= num_V_214_fu_1977_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        num_V_216_reg_2868 <= num_V_216_fu_2039_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        r_V_308_reg_2381 <= grp_fu_1872_p_dout0;
        r_V_reg_2370 <= grp_fu_1868_p_dout0;
        trunc_ln727_104_reg_2387 <= trunc_ln727_104_fu_682_p1;
        trunc_ln727_reg_2376 <= trunc_ln727_fu_678_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln285_reg_2128 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_482 <= m_0_q1;
        reg_486 <= m_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln285_fu_503_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_s_reg_2132[7 : 4] <= tmp_s_fu_535_p3[7 : 4];
    end
end

always @ (*) begin
    if (((icmp_ln285_reg_2128 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage14_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_8 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_8 = i_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_sig_allocacmp_lhs_load_7 = num_V_fu_2098_p2;
    end else begin
        ap_sig_allocacmp_lhs_load_7 = lhs_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_0_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_10_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_11_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_12_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_13_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_14_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_15_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_1_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_2_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_3_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_4_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_5_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_6_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_7_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_8_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_14_9_ce0 = 1'b1;
    end else begin
        firstDense_f_V_14_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            m_0_address0 = tmp_103_fu_1138_p3;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            m_0_address0 = tmp_101_fu_1004_p3;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            m_0_address0 = tmp_99_fu_870_p3;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            m_0_address0 = tmp_97_fu_734_p3;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            m_0_address0 = tmp_95_fu_669_p3;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            m_0_address0 = tmp_93_fu_615_p3;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            m_0_address0 = tmp_91_fu_587_p3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            m_0_address0 = tmp_89_fu_554_p3;
        end else begin
            m_0_address0 = 'bx;
        end
    end else begin
        m_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            m_0_address1 = tmp_102_fu_1124_p3;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            m_0_address1 = tmp_100_fu_990_p3;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            m_0_address1 = tmp_98_fu_856_p3;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            m_0_address1 = tmp_96_fu_720_p3;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            m_0_address1 = tmp_94_fu_655_p3;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            m_0_address1 = tmp_92_fu_601_p3;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            m_0_address1 = tmp_90_fu_573_p3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            m_0_address1 = zext_ln289_fu_543_p1;
        end else begin
            m_0_address1 = 'bx;
        end
    end else begin
        m_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_0_ce0 = 1'b1;
    end else begin
        m_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_0_ce1 = 1'b1;
    end else begin
        m_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln285_reg_2128 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        num_V_992_out_ap_vld = 1'b1;
    end else begin
        num_V_992_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln285_fu_509_p2 = (ap_sig_allocacmp_i_8 + 4'd1);

assign and_ln412_77_fu_925_p2 = (p_Result_316_fu_913_p3 & or_ln412_76_fu_920_p2);

assign and_ln412_78_fu_1059_p2 = (p_Result_317_fu_1047_p3 & or_ln412_77_fu_1054_p2);

assign and_ln412_79_fu_1193_p2 = (p_Result_318_fu_1181_p3 & or_ln412_78_fu_1188_p2);

assign and_ln412_80_fu_1296_p2 = (p_Result_319_fu_1283_p3 & or_ln412_79_fu_1291_p2);

assign and_ln412_81_fu_1402_p2 = (p_Result_320_fu_1390_p3 & or_ln412_80_fu_1397_p2);

assign and_ln412_82_fu_1508_p2 = (p_Result_321_fu_1496_p3 & or_ln412_81_fu_1503_p2);

assign and_ln412_83_fu_1588_p2 = (p_Result_322_fu_1576_p3 & or_ln412_82_fu_1583_p2);

assign and_ln412_84_fu_1660_p2 = (p_Result_323_fu_1648_p3 & or_ln412_83_fu_1655_p2);

assign and_ln412_85_fu_1722_p2 = (p_Result_324_fu_1710_p3 & or_ln412_84_fu_1717_p2);

assign and_ln412_86_fu_1781_p2 = (p_Result_325_fu_1768_p3 & or_ln412_85_fu_1776_p2);

assign and_ln412_87_fu_1843_p2 = (p_Result_326_fu_1831_p3 & or_ln412_86_fu_1838_p2);

assign and_ln412_88_fu_1905_p2 = (p_Result_327_fu_1893_p3 & or_ln412_87_fu_1900_p2);

assign and_ln412_89_fu_1967_p2 = (p_Result_328_fu_1955_p3 & or_ln412_88_fu_1962_p2);

assign and_ln412_90_fu_2029_p2 = (p_Result_329_fu_2017_p3 & or_ln412_89_fu_2024_p2);

assign and_ln412_91_fu_2088_p2 = (p_Result_330_fu_2075_p3 & or_ln412_90_fu_2083_p2);

assign and_ln412_fu_796_p2 = (p_Result_315_fu_778_p3 & or_ln412_fu_790_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage11_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage12_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage13_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage14_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign firstDense_f_V_14_0_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_10_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_11_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_12_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_13_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_14_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_15_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_1_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_2_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_3_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_4_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_5_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_6_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_7_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_8_address0 = i_18_cast_fu_515_p1;

assign firstDense_f_V_14_9_address0 = i_18_cast_fu_515_p1;

assign grp_fu_1868_p_ce = 1'b1;

assign grp_fu_1868_p_din0 = sext_ln1171_fu_628_p1;

assign grp_fu_1868_p_din1 = zext_ln1168_fu_624_p1;

assign grp_fu_1872_p_ce = 1'b1;

assign grp_fu_1872_p_din0 = sext_ln1171_76_fu_641_p1;

assign grp_fu_1872_p_din1 = zext_ln1168_63_fu_637_p1;

assign grp_fu_1876_p_ce = 1'b1;

assign grp_fu_1876_p_din0 = sext_ln1171_77_fu_690_p1;

assign grp_fu_1876_p_din1 = zext_ln1168_64_fu_686_p1;

assign grp_fu_1880_p_ce = 1'b1;

assign grp_fu_1880_p_din0 = sext_ln1171_78_fu_703_p1;

assign grp_fu_1880_p_din1 = zext_ln1168_65_fu_699_p1;

assign grp_fu_1884_p_ce = 1'b1;

assign grp_fu_1884_p_din0 = sext_ln1171_80_fu_842_p1;

assign grp_fu_1884_p_din1 = zext_ln1168_67_fu_838_p1;

assign grp_fu_1888_p_ce = 1'b1;

assign grp_fu_1888_p_din0 = sext_ln1171_81_fu_963_p1;

assign grp_fu_1888_p_din1 = zext_ln1168_68_fu_959_p1;

assign grp_fu_1892_p_ce = 1'b1;

assign grp_fu_1892_p_din0 = sext_ln1171_83_fu_1097_p1;

assign grp_fu_1892_p_din1 = zext_ln1168_70_fu_1093_p1;

assign grp_fu_1896_p_ce = 1'b1;

assign grp_fu_1896_p_din0 = sext_ln1171_79_fu_829_p1;

assign grp_fu_1896_p_din1 = zext_ln1168_66_fu_825_p1;

assign grp_fu_1900_p_ce = 1'b1;

assign grp_fu_1900_p_din0 = sext_ln1171_84_fu_1110_p1;

assign grp_fu_1900_p_din1 = zext_ln1168_71_fu_1106_p1;

assign grp_fu_1904_p_ce = 1'b1;

assign grp_fu_1904_p_din0 = sext_ln1171_85_fu_1231_p1;

assign grp_fu_1904_p_din1 = zext_ln1168_72_fu_1227_p1;

assign grp_fu_1912_p_ce = 1'b1;

assign grp_fu_1912_p_din0 = sext_ln1171_90_fu_1453_p1;

assign grp_fu_1912_p_din1 = zext_ln1168_77_fu_1449_p1;

assign grp_fu_1916_p_ce = 1'b1;

assign grp_fu_1916_p_din0 = sext_ln1171_82_fu_976_p1;

assign grp_fu_1916_p_din1 = zext_ln1168_69_fu_972_p1;

assign grp_fu_1972_p_ce = 1'b1;

assign grp_fu_1972_p_din0 = sext_ln1171_86_fu_1244_p1;

assign grp_fu_1972_p_din1 = zext_ln1168_73_fu_1240_p1;

assign grp_fu_2004_p_ce = 1'b1;

assign grp_fu_2004_p_din0 = sext_ln1171_87_fu_1334_p1;

assign grp_fu_2004_p_din1 = zext_ln1168_74_fu_1330_p1;

assign grp_fu_2008_p_ce = 1'b1;

assign grp_fu_2008_p_din0 = sext_ln1171_88_fu_1347_p1;

assign grp_fu_2008_p_din1 = zext_ln1168_75_fu_1343_p1;

assign grp_fu_2012_p_ce = 1'b1;

assign grp_fu_2012_p_din0 = sext_ln1171_89_fu_1440_p1;

assign grp_fu_2012_p_din1 = zext_ln1168_76_fu_1436_p1;

assign i_18_cast_fu_515_p1 = ap_sig_allocacmp_i_8;

assign icmp_ln285_fu_503_p2 = ((ap_sig_allocacmp_i_8 == 4'd14) ? 1'b1 : 1'b0);

assign lhs_188_fu_743_p3 = {{ap_sig_allocacmp_lhs_load_7}, {19'd0}};

assign lhs_190_fu_879_p3 = {{num_V_188_reg_2422}, {19'd0}};

assign lhs_192_fu_1013_p3 = {{num_V_190_reg_2484}, {19'd0}};

assign lhs_194_fu_1147_p3 = {{num_V_192_reg_2550}, {19'd0}};

assign lhs_196_fu_1253_p3 = {{num_V_194_reg_2617}, {19'd0}};

assign lhs_198_fu_1356_p3 = {{num_V_196_reg_2674}, {19'd0}};

assign lhs_200_fu_1462_p3 = {{num_V_198_reg_2730}, {19'd0}};

assign lhs_202_fu_1542_p3 = {{num_V_200_reg_2787}, {19'd0}};

assign lhs_204_fu_1614_p3 = {{num_V_202_reg_2823}, {19'd0}};

assign lhs_206_fu_1676_p3 = {{num_V_204_reg_2838}, {19'd0}};

assign lhs_208_fu_1738_p3 = {{num_V_206_reg_2843}, {19'd0}};

assign lhs_210_fu_1797_p3 = {{num_V_208_reg_2848}, {19'd0}};

assign lhs_212_fu_1859_p3 = {{num_V_210_reg_2853}, {19'd0}};

assign lhs_214_fu_1921_p3 = {{num_V_212_reg_2858}, {19'd0}};

assign lhs_216_fu_1983_p3 = {{num_V_214_reg_2863}, {19'd0}};

assign lhs_218_fu_2045_p3 = {{num_V_216_reg_2868}, {19'd0}};

assign num_V_187_fu_760_p4 = {{ret_V_fu_754_p2[54:19]}};

assign num_V_188_fu_806_p2 = (num_V_187_fu_760_p4 + zext_ln415_fu_802_p1);

assign num_V_189_fu_895_p4 = {{ret_V_91_fu_889_p2[54:19]}};

assign num_V_190_fu_935_p2 = (num_V_189_fu_895_p4 + zext_ln415_76_fu_931_p1);

assign num_V_191_fu_1029_p4 = {{ret_V_92_fu_1023_p2[54:19]}};

assign num_V_192_fu_1069_p2 = (num_V_191_fu_1029_p4 + zext_ln415_77_fu_1065_p1);

assign num_V_193_fu_1163_p4 = {{ret_V_93_fu_1157_p2[54:19]}};

assign num_V_194_fu_1203_p2 = (num_V_193_fu_1163_p4 + zext_ln415_78_fu_1199_p1);

assign num_V_195_fu_1265_p4 = {{ret_V_94_fu_1260_p2[54:19]}};

assign num_V_196_fu_1306_p2 = (num_V_195_fu_1265_p4 + zext_ln415_79_fu_1302_p1);

assign num_V_197_fu_1372_p4 = {{ret_V_95_fu_1366_p2[54:19]}};

assign num_V_198_fu_1412_p2 = (num_V_197_fu_1372_p4 + zext_ln415_80_fu_1408_p1);

assign num_V_199_fu_1478_p4 = {{ret_V_96_fu_1472_p2[54:19]}};

assign num_V_200_fu_1518_p2 = (num_V_199_fu_1478_p4 + zext_ln415_81_fu_1514_p1);

assign num_V_201_fu_1558_p4 = {{ret_V_97_fu_1552_p2[54:19]}};

assign num_V_202_fu_1598_p2 = (num_V_201_fu_1558_p4 + zext_ln415_82_fu_1594_p1);

assign num_V_203_fu_1630_p4 = {{ret_V_98_fu_1624_p2[54:19]}};

assign num_V_204_fu_1670_p2 = (num_V_203_fu_1630_p4 + zext_ln415_83_fu_1666_p1);

assign num_V_205_fu_1692_p4 = {{ret_V_99_fu_1686_p2[54:19]}};

assign num_V_206_fu_1732_p2 = (num_V_205_fu_1692_p4 + zext_ln415_84_fu_1728_p1);

assign num_V_207_fu_1750_p4 = {{ret_V_100_fu_1745_p2[54:19]}};

assign num_V_208_fu_1791_p2 = (num_V_207_fu_1750_p4 + zext_ln415_85_fu_1787_p1);

assign num_V_209_fu_1813_p4 = {{ret_V_101_fu_1807_p2[54:19]}};

assign num_V_210_fu_1853_p2 = (num_V_209_fu_1813_p4 + zext_ln415_86_fu_1849_p1);

assign num_V_211_fu_1875_p4 = {{ret_V_102_fu_1869_p2[54:19]}};

assign num_V_212_fu_1915_p2 = (num_V_211_fu_1875_p4 + zext_ln415_87_fu_1911_p1);

assign num_V_213_fu_1937_p4 = {{ret_V_103_fu_1931_p2[54:19]}};

assign num_V_214_fu_1977_p2 = (num_V_213_fu_1937_p4 + zext_ln415_88_fu_1973_p1);

assign num_V_215_fu_1999_p4 = {{ret_V_104_fu_1993_p2[54:19]}};

assign num_V_216_fu_2039_p2 = (num_V_215_fu_1999_p4 + zext_ln415_89_fu_2035_p1);

assign num_V_217_fu_2057_p4 = {{ret_V_105_fu_2052_p2[54:19]}};

assign num_V_992_out = lhs_fu_122;

assign num_V_fu_2098_p2 = (num_V_217_fu_2057_p4 + zext_ln415_90_fu_2094_p1);

assign or_ln289_58_fu_568_p2 = (tmp_s_reg_2132 | 8'd2);

assign or_ln289_59_fu_582_p2 = (tmp_s_reg_2132 | 8'd3);

assign or_ln289_60_fu_596_p2 = (tmp_s_reg_2132 | 8'd4);

assign or_ln289_61_fu_610_p2 = (tmp_s_reg_2132 | 8'd5);

assign or_ln289_62_fu_650_p2 = (tmp_s_reg_2132 | 8'd6);

assign or_ln289_63_fu_664_p2 = (tmp_s_reg_2132 | 8'd7);

assign or_ln289_64_fu_715_p2 = (tmp_s_reg_2132 | 8'd8);

assign or_ln289_65_fu_729_p2 = (tmp_s_reg_2132 | 8'd9);

assign or_ln289_66_fu_851_p2 = (tmp_s_reg_2132 | 8'd10);

assign or_ln289_67_fu_865_p2 = (tmp_s_reg_2132 | 8'd11);

assign or_ln289_68_fu_985_p2 = (tmp_s_reg_2132 | 8'd12);

assign or_ln289_69_fu_999_p2 = (tmp_s_reg_2132 | 8'd13);

assign or_ln289_70_fu_1119_p2 = (tmp_s_reg_2132 | 8'd14);

assign or_ln289_71_fu_1133_p2 = (tmp_s_reg_2132 | 8'd15);

assign or_ln289_fu_548_p2 = (tmp_s_fu_535_p3 | 8'd1);

assign or_ln412_76_fu_920_p2 = (r_93_reg_2427 | p_Result_286_fu_905_p3);

assign or_ln412_77_fu_1054_p2 = (r_94_reg_2489 | p_Result_288_fu_1039_p3);

assign or_ln412_78_fu_1188_p2 = (r_95_reg_2494 | p_Result_290_fu_1173_p3);

assign or_ln412_79_fu_1291_p2 = (r_96_reg_2555 | p_Result_292_fu_1275_p3);

assign or_ln412_80_fu_1397_p2 = (r_97_reg_2560 | p_Result_294_fu_1382_p3);

assign or_ln412_81_fu_1503_p2 = (r_98_reg_2622 | p_Result_296_fu_1488_p3);

assign or_ln412_82_fu_1583_p2 = (r_99_reg_2627 | p_Result_298_fu_1568_p3);

assign or_ln412_83_fu_1655_p2 = (r_100_reg_2679 | p_Result_300_fu_1640_p3);

assign or_ln412_84_fu_1717_p2 = (r_101_reg_2684 | p_Result_302_fu_1702_p3);

assign or_ln412_85_fu_1776_p2 = (r_102_reg_2735 | p_Result_304_fu_1760_p3);

assign or_ln412_86_fu_1838_p2 = (r_103_reg_2740 | p_Result_306_fu_1823_p3);

assign or_ln412_87_fu_1900_p2 = (r_104_reg_2792 | p_Result_308_fu_1885_p3);

assign or_ln412_88_fu_1962_p2 = (r_105_reg_2797 | p_Result_310_fu_1947_p3);

assign or_ln412_89_fu_2024_p2 = (r_106_reg_2828 | p_Result_312_fu_2009_p3);

assign or_ln412_90_fu_2083_p2 = (r_107_reg_2833 | p_Result_314_fu_2067_p3);

assign or_ln412_fu_790_p2 = (r_fu_785_p2 | p_Result_s_fu_770_p3);

assign p_Result_286_fu_905_p3 = ret_V_91_fu_889_p2[32'd19];

assign p_Result_288_fu_1039_p3 = ret_V_92_fu_1023_p2[32'd19];

assign p_Result_290_fu_1173_p3 = ret_V_93_fu_1157_p2[32'd19];

assign p_Result_292_fu_1275_p3 = ret_V_94_fu_1260_p2[32'd19];

assign p_Result_294_fu_1382_p3 = ret_V_95_fu_1366_p2[32'd19];

assign p_Result_296_fu_1488_p3 = ret_V_96_fu_1472_p2[32'd19];

assign p_Result_298_fu_1568_p3 = ret_V_97_fu_1552_p2[32'd19];

assign p_Result_300_fu_1640_p3 = ret_V_98_fu_1624_p2[32'd19];

assign p_Result_302_fu_1702_p3 = ret_V_99_fu_1686_p2[32'd19];

assign p_Result_304_fu_1760_p3 = ret_V_100_fu_1745_p2[32'd19];

assign p_Result_306_fu_1823_p3 = ret_V_101_fu_1807_p2[32'd19];

assign p_Result_308_fu_1885_p3 = ret_V_102_fu_1869_p2[32'd19];

assign p_Result_310_fu_1947_p3 = ret_V_103_fu_1931_p2[32'd19];

assign p_Result_312_fu_2009_p3 = ret_V_104_fu_1993_p2[32'd19];

assign p_Result_314_fu_2067_p3 = ret_V_105_fu_2052_p2[32'd19];

assign p_Result_315_fu_778_p3 = r_V_reg_2370[32'd18];

assign p_Result_316_fu_913_p3 = r_V_308_reg_2381[32'd18];

assign p_Result_317_fu_1047_p3 = r_V_309_reg_2432[32'd18];

assign p_Result_318_fu_1181_p3 = r_V_310_reg_2443[32'd18];

assign p_Result_319_fu_1283_p3 = ret_V_94_fu_1260_p2[32'd18];

assign p_Result_320_fu_1390_p3 = r_V_312_reg_2509[32'd18];

assign p_Result_321_fu_1496_p3 = r_V_313_reg_2565[32'd18];

assign p_Result_322_fu_1576_p3 = r_V_314_reg_2576[32'd18];

assign p_Result_323_fu_1648_p3 = r_V_315_reg_2632[32'd18];

assign p_Result_324_fu_1710_p3 = r_V_316_reg_2643[32'd18];

assign p_Result_325_fu_1768_p3 = ret_V_100_fu_1745_p2[32'd18];

assign p_Result_326_fu_1831_p3 = r_V_318_reg_2699[32'd18];

assign p_Result_327_fu_1893_p3 = r_V_319_reg_2745[32'd18];

assign p_Result_328_fu_1955_p3 = r_V_320_reg_2756[32'd18];

assign p_Result_329_fu_2017_p3 = r_V_321_reg_2802[32'd18];

assign p_Result_330_fu_2075_p3 = ret_V_105_fu_2052_p2[32'd18];

assign p_Result_s_fu_770_p3 = ret_V_fu_754_p2[32'd19];

assign r_100_fu_1312_p2 = ((trunc_ln727_111_reg_2638 != 18'd0) ? 1'b1 : 1'b0);

assign r_101_fu_1317_p2 = ((trunc_ln727_112_reg_2649 != 18'd0) ? 1'b1 : 1'b0);

assign r_102_fu_1418_p2 = ((trunc_ln727_113_reg_2694 != 18'd0) ? 1'b1 : 1'b0);

assign r_103_fu_1423_p2 = ((trunc_ln727_114_reg_2705 != 18'd0) ? 1'b1 : 1'b0);

assign r_104_fu_1524_p2 = ((trunc_ln727_115_reg_2751 != 18'd0) ? 1'b1 : 1'b0);

assign r_105_fu_1529_p2 = ((trunc_ln727_116_reg_2762 != 18'd0) ? 1'b1 : 1'b0);

assign r_106_fu_1604_p2 = ((trunc_ln727_117_reg_2808 != 18'd0) ? 1'b1 : 1'b0);

assign r_107_fu_1609_p2 = ((trunc_ln727_118_reg_2818 != 18'd0) ? 1'b1 : 1'b0);

assign r_93_fu_812_p2 = ((trunc_ln727_104_reg_2387 != 18'd0) ? 1'b1 : 1'b0);

assign r_94_fu_941_p2 = ((trunc_ln727_105_reg_2438 != 18'd0) ? 1'b1 : 1'b0);

assign r_95_fu_946_p2 = ((trunc_ln727_106_reg_2449 != 18'd0) ? 1'b1 : 1'b0);

assign r_96_fu_1075_p2 = ((trunc_ln727_107_reg_2504 != 18'd0) ? 1'b1 : 1'b0);

assign r_97_fu_1080_p2 = ((trunc_ln727_108_reg_2515 != 18'd0) ? 1'b1 : 1'b0);

assign r_98_fu_1209_p2 = ((trunc_ln727_109_reg_2571 != 18'd0) ? 1'b1 : 1'b0);

assign r_99_fu_1214_p2 = ((trunc_ln727_110_reg_2582 != 18'd0) ? 1'b1 : 1'b0);

assign r_fu_785_p2 = ((trunc_ln727_reg_2376 != 18'd0) ? 1'b1 : 1'b0);

assign ret_V_100_fu_1745_p2 = (lhs_208_fu_1738_p3 + r_V_317_reg_2689);

assign ret_V_101_fu_1807_p2 = ($signed(lhs_210_fu_1797_p3) + $signed(sext_ln1245_60_fu_1804_p1));

assign ret_V_102_fu_1869_p2 = ($signed(lhs_212_fu_1859_p3) + $signed(sext_ln1245_61_fu_1866_p1));

assign ret_V_103_fu_1931_p2 = ($signed(lhs_214_fu_1921_p3) + $signed(sext_ln1245_62_fu_1928_p1));

assign ret_V_104_fu_1993_p2 = ($signed(lhs_216_fu_1983_p3) + $signed(sext_ln1245_63_fu_1990_p1));

assign ret_V_105_fu_2052_p2 = (lhs_218_fu_2045_p3 + r_V_322_reg_2813);

assign ret_V_91_fu_889_p2 = ($signed(lhs_190_fu_879_p3) + $signed(sext_ln1245_52_fu_886_p1));

assign ret_V_92_fu_1023_p2 = ($signed(lhs_192_fu_1013_p3) + $signed(sext_ln1245_53_fu_1020_p1));

assign ret_V_93_fu_1157_p2 = ($signed(lhs_194_fu_1147_p3) + $signed(sext_ln1245_54_fu_1154_p1));

assign ret_V_94_fu_1260_p2 = (lhs_196_fu_1253_p3 + r_V_311_reg_2499);

assign ret_V_95_fu_1366_p2 = ($signed(lhs_198_fu_1356_p3) + $signed(sext_ln1245_55_fu_1363_p1));

assign ret_V_96_fu_1472_p2 = ($signed(lhs_200_fu_1462_p3) + $signed(sext_ln1245_56_fu_1469_p1));

assign ret_V_97_fu_1552_p2 = ($signed(lhs_202_fu_1542_p3) + $signed(sext_ln1245_57_fu_1549_p1));

assign ret_V_98_fu_1624_p2 = ($signed(lhs_204_fu_1614_p3) + $signed(sext_ln1245_58_fu_1621_p1));

assign ret_V_99_fu_1686_p2 = ($signed(lhs_206_fu_1676_p3) + $signed(sext_ln1245_59_fu_1683_p1));

assign ret_V_fu_754_p2 = ($signed(lhs_188_fu_743_p3) + $signed(sext_ln1245_fu_751_p1));

assign sext_ln1171_76_fu_641_p1 = $signed(aux2_V_93_reg_2255);

assign sext_ln1171_77_fu_690_p1 = $signed(aux2_V_94_reg_2260);

assign sext_ln1171_78_fu_703_p1 = $signed(aux2_V_95_reg_2265);

assign sext_ln1171_79_fu_829_p1 = $signed(aux2_V_96_reg_2270);

assign sext_ln1171_80_fu_842_p1 = $signed(aux2_V_97_reg_2275);

assign sext_ln1171_81_fu_963_p1 = $signed(aux2_V_98_reg_2280);

assign sext_ln1171_82_fu_976_p1 = $signed(aux2_V_99_reg_2285);

assign sext_ln1171_83_fu_1097_p1 = $signed(aux2_V_100_reg_2290);

assign sext_ln1171_84_fu_1110_p1 = $signed(aux2_V_101_reg_2295);

assign sext_ln1171_85_fu_1231_p1 = $signed(aux2_V_102_reg_2300);

assign sext_ln1171_86_fu_1244_p1 = $signed(aux2_V_103_reg_2305);

assign sext_ln1171_87_fu_1334_p1 = $signed(aux2_V_104_reg_2310);

assign sext_ln1171_88_fu_1347_p1 = $signed(aux2_V_105_reg_2315);

assign sext_ln1171_89_fu_1440_p1 = $signed(aux2_V_106_reg_2320);

assign sext_ln1171_90_fu_1453_p1 = $signed(aux2_V_107_reg_2325);

assign sext_ln1171_fu_628_p1 = $signed(aux2_V_reg_2250);

assign sext_ln1245_52_fu_886_p1 = r_V_308_reg_2381;

assign sext_ln1245_53_fu_1020_p1 = r_V_309_reg_2432;

assign sext_ln1245_54_fu_1154_p1 = r_V_310_reg_2443;

assign sext_ln1245_55_fu_1363_p1 = r_V_312_reg_2509;

assign sext_ln1245_56_fu_1469_p1 = r_V_313_reg_2565;

assign sext_ln1245_57_fu_1549_p1 = r_V_314_reg_2576;

assign sext_ln1245_58_fu_1621_p1 = r_V_315_reg_2632;

assign sext_ln1245_59_fu_1683_p1 = r_V_316_reg_2643;

assign sext_ln1245_60_fu_1804_p1 = r_V_318_reg_2699;

assign sext_ln1245_61_fu_1866_p1 = r_V_319_reg_2745;

assign sext_ln1245_62_fu_1928_p1 = r_V_320_reg_2756;

assign sext_ln1245_63_fu_1990_p1 = r_V_321_reg_2802;

assign sext_ln1245_fu_751_p1 = r_V_reg_2370;

assign tmp_100_fu_990_p3 = {{56'd0}, {or_ln289_68_fu_985_p2}};

assign tmp_101_fu_1004_p3 = {{56'd0}, {or_ln289_69_fu_999_p2}};

assign tmp_102_fu_1124_p3 = {{56'd0}, {or_ln289_70_fu_1119_p2}};

assign tmp_103_fu_1138_p3 = {{56'd0}, {or_ln289_71_fu_1133_p2}};

assign tmp_89_fu_554_p3 = {{56'd0}, {or_ln289_fu_548_p2}};

assign tmp_90_fu_573_p3 = {{56'd0}, {or_ln289_58_fu_568_p2}};

assign tmp_91_fu_587_p3 = {{56'd0}, {or_ln289_59_fu_582_p2}};

assign tmp_92_fu_601_p3 = {{56'd0}, {or_ln289_60_fu_596_p2}};

assign tmp_93_fu_615_p3 = {{56'd0}, {or_ln289_61_fu_610_p2}};

assign tmp_94_fu_655_p3 = {{56'd0}, {or_ln289_62_fu_650_p2}};

assign tmp_95_fu_669_p3 = {{56'd0}, {or_ln289_63_fu_664_p2}};

assign tmp_96_fu_720_p3 = {{56'd0}, {or_ln289_64_fu_715_p2}};

assign tmp_97_fu_734_p3 = {{56'd0}, {or_ln289_65_fu_729_p2}};

assign tmp_98_fu_856_p3 = {{56'd0}, {or_ln289_66_fu_851_p2}};

assign tmp_99_fu_870_p3 = {{56'd0}, {or_ln289_67_fu_865_p2}};

assign tmp_s_fu_535_p3 = {{ap_sig_allocacmp_i_8}, {4'd0}};

assign trunc_ln727_104_fu_682_p1 = grp_fu_1872_p_dout0[17:0];

assign trunc_ln727_105_fu_817_p1 = grp_fu_1876_p_dout0[17:0];

assign trunc_ln727_106_fu_821_p1 = grp_fu_1880_p_dout0[17:0];

assign trunc_ln727_107_fu_951_p1 = grp_fu_1896_p_dout0[17:0];

assign trunc_ln727_108_fu_955_p1 = grp_fu_1884_p_dout0[17:0];

assign trunc_ln727_109_fu_1085_p1 = grp_fu_1888_p_dout0[17:0];

assign trunc_ln727_110_fu_1089_p1 = grp_fu_1916_p_dout0[17:0];

assign trunc_ln727_111_fu_1219_p1 = grp_fu_1892_p_dout0[17:0];

assign trunc_ln727_112_fu_1223_p1 = grp_fu_1900_p_dout0[17:0];

assign trunc_ln727_113_fu_1322_p1 = grp_fu_1904_p_dout0[17:0];

assign trunc_ln727_114_fu_1326_p1 = grp_fu_1972_p_dout0[17:0];

assign trunc_ln727_115_fu_1428_p1 = grp_fu_2004_p_dout0[17:0];

assign trunc_ln727_116_fu_1432_p1 = grp_fu_2008_p_dout0[17:0];

assign trunc_ln727_117_fu_1534_p1 = grp_fu_2012_p_dout0[17:0];

assign trunc_ln727_118_fu_1538_p1 = grp_fu_1912_p_dout0[17:0];

assign trunc_ln727_fu_678_p1 = grp_fu_1868_p_dout0[17:0];

assign zext_ln1168_63_fu_637_p1 = reg_486;

assign zext_ln1168_64_fu_686_p1 = reg_482;

assign zext_ln1168_65_fu_699_p1 = reg_486;

assign zext_ln1168_66_fu_825_p1 = reg_482;

assign zext_ln1168_67_fu_838_p1 = reg_486;

assign zext_ln1168_68_fu_959_p1 = reg_482;

assign zext_ln1168_69_fu_972_p1 = reg_486;

assign zext_ln1168_70_fu_1093_p1 = reg_482;

assign zext_ln1168_71_fu_1106_p1 = reg_486;

assign zext_ln1168_72_fu_1227_p1 = reg_482;

assign zext_ln1168_73_fu_1240_p1 = reg_486;

assign zext_ln1168_74_fu_1330_p1 = reg_482;

assign zext_ln1168_75_fu_1343_p1 = reg_486;

assign zext_ln1168_76_fu_1436_p1 = reg_482;

assign zext_ln1168_77_fu_1449_p1 = reg_486;

assign zext_ln1168_fu_624_p1 = reg_482;

assign zext_ln289_fu_543_p1 = tmp_s_fu_535_p3;

assign zext_ln415_76_fu_931_p1 = and_ln412_77_fu_925_p2;

assign zext_ln415_77_fu_1065_p1 = and_ln412_78_fu_1059_p2;

assign zext_ln415_78_fu_1199_p1 = and_ln412_79_fu_1193_p2;

assign zext_ln415_79_fu_1302_p1 = and_ln412_80_fu_1296_p2;

assign zext_ln415_80_fu_1408_p1 = and_ln412_81_fu_1402_p2;

assign zext_ln415_81_fu_1514_p1 = and_ln412_82_fu_1508_p2;

assign zext_ln415_82_fu_1594_p1 = and_ln412_83_fu_1588_p2;

assign zext_ln415_83_fu_1666_p1 = and_ln412_84_fu_1660_p2;

assign zext_ln415_84_fu_1728_p1 = and_ln412_85_fu_1722_p2;

assign zext_ln415_85_fu_1787_p1 = and_ln412_86_fu_1781_p2;

assign zext_ln415_86_fu_1849_p1 = and_ln412_87_fu_1843_p2;

assign zext_ln415_87_fu_1911_p1 = and_ln412_88_fu_1905_p2;

assign zext_ln415_88_fu_1973_p1 = and_ln412_89_fu_1967_p2;

assign zext_ln415_89_fu_2035_p1 = and_ln412_90_fu_2029_p2;

assign zext_ln415_90_fu_2094_p1 = and_ln412_91_fu_2088_p2;

assign zext_ln415_fu_802_p1 = and_ln412_fu_796_p2;

always @ (posedge ap_clk) begin
    tmp_s_reg_2132[3:0] <= 4'b0000;
end

endmodule //master_fix_dense1_fix_Pipeline_Dense1_Loop218
