// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module master_fix_dense1_fix_Pipeline_Dense1_Loop216 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_0_address0,
        m_0_ce0,
        m_0_q0,
        m_0_address1,
        m_0_ce1,
        m_0_q1,
        num_V_928_out,
        num_V_928_out_ap_vld,
        grp_fu_1872_p_din0,
        grp_fu_1872_p_din1,
        grp_fu_1872_p_dout0,
        grp_fu_1872_p_ce,
        grp_fu_1892_p_din0,
        grp_fu_1892_p_din1,
        grp_fu_1892_p_dout0,
        grp_fu_1892_p_ce,
        grp_fu_1868_p_din0,
        grp_fu_1868_p_din1,
        grp_fu_1868_p_dout0,
        grp_fu_1868_p_ce,
        grp_fu_1876_p_din0,
        grp_fu_1876_p_din1,
        grp_fu_1876_p_dout0,
        grp_fu_1876_p_ce,
        grp_fu_1880_p_din0,
        grp_fu_1880_p_din1,
        grp_fu_1880_p_dout0,
        grp_fu_1880_p_ce,
        grp_fu_1884_p_din0,
        grp_fu_1884_p_din1,
        grp_fu_1884_p_dout0,
        grp_fu_1884_p_ce,
        grp_fu_1896_p_din0,
        grp_fu_1896_p_din1,
        grp_fu_1896_p_dout0,
        grp_fu_1896_p_ce,
        grp_fu_1888_p_din0,
        grp_fu_1888_p_din1,
        grp_fu_1888_p_dout0,
        grp_fu_1888_p_ce,
        grp_fu_1916_p_din0,
        grp_fu_1916_p_din1,
        grp_fu_1916_p_dout0,
        grp_fu_1916_p_ce,
        grp_fu_1972_p_din0,
        grp_fu_1972_p_din1,
        grp_fu_1972_p_dout0,
        grp_fu_1972_p_ce,
        grp_fu_1900_p_din0,
        grp_fu_1900_p_din1,
        grp_fu_1900_p_dout0,
        grp_fu_1900_p_ce,
        grp_fu_1968_p_din0,
        grp_fu_1968_p_din1,
        grp_fu_1968_p_dout0,
        grp_fu_1968_p_ce,
        grp_fu_2004_p_din0,
        grp_fu_2004_p_din1,
        grp_fu_2004_p_dout0,
        grp_fu_2004_p_ce,
        grp_fu_1904_p_din0,
        grp_fu_1904_p_din1,
        grp_fu_1904_p_dout0,
        grp_fu_1904_p_ce,
        grp_fu_2008_p_din0,
        grp_fu_2008_p_din1,
        grp_fu_2008_p_dout0,
        grp_fu_2008_p_ce,
        grp_fu_1908_p_din0,
        grp_fu_1908_p_din1,
        grp_fu_1908_p_dout0,
        grp_fu_1908_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 15'd1;
parameter    ap_ST_fsm_pp0_stage1 = 15'd2;
parameter    ap_ST_fsm_pp0_stage2 = 15'd4;
parameter    ap_ST_fsm_pp0_stage3 = 15'd8;
parameter    ap_ST_fsm_pp0_stage4 = 15'd16;
parameter    ap_ST_fsm_pp0_stage5 = 15'd32;
parameter    ap_ST_fsm_pp0_stage6 = 15'd64;
parameter    ap_ST_fsm_pp0_stage7 = 15'd128;
parameter    ap_ST_fsm_pp0_stage8 = 15'd256;
parameter    ap_ST_fsm_pp0_stage9 = 15'd512;
parameter    ap_ST_fsm_pp0_stage10 = 15'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 15'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 15'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 15'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] m_0_address0;
output   m_0_ce0;
input  [34:0] m_0_q0;
output  [7:0] m_0_address1;
output   m_0_ce1;
input  [34:0] m_0_q1;
output  [35:0] num_V_928_out;
output   num_V_928_out_ap_vld;
output  [17:0] grp_fu_1872_p_din0;
output  [34:0] grp_fu_1872_p_din1;
input  [52:0] grp_fu_1872_p_dout0;
output   grp_fu_1872_p_ce;
output  [17:0] grp_fu_1892_p_din0;
output  [34:0] grp_fu_1892_p_din1;
input  [52:0] grp_fu_1892_p_dout0;
output   grp_fu_1892_p_ce;
output  [19:0] grp_fu_1868_p_din0;
output  [34:0] grp_fu_1868_p_din1;
input  [53:0] grp_fu_1868_p_dout0;
output   grp_fu_1868_p_ce;
output  [18:0] grp_fu_1876_p_din0;
output  [34:0] grp_fu_1876_p_din1;
input  [53:0] grp_fu_1876_p_dout0;
output   grp_fu_1876_p_ce;
output  [18:0] grp_fu_1880_p_din0;
output  [34:0] grp_fu_1880_p_din1;
input  [53:0] grp_fu_1880_p_dout0;
output   grp_fu_1880_p_ce;
output  [18:0] grp_fu_1884_p_din0;
output  [34:0] grp_fu_1884_p_din1;
input  [53:0] grp_fu_1884_p_dout0;
output   grp_fu_1884_p_ce;
output  [19:0] grp_fu_1896_p_din0;
output  [34:0] grp_fu_1896_p_din1;
input  [54:0] grp_fu_1896_p_dout0;
output   grp_fu_1896_p_ce;
output  [18:0] grp_fu_1888_p_din0;
output  [34:0] grp_fu_1888_p_din1;
input  [53:0] grp_fu_1888_p_dout0;
output   grp_fu_1888_p_ce;
output  [18:0] grp_fu_1916_p_din0;
output  [34:0] grp_fu_1916_p_din1;
input  [53:0] grp_fu_1916_p_dout0;
output   grp_fu_1916_p_ce;
output  [18:0] grp_fu_1972_p_din0;
output  [34:0] grp_fu_1972_p_din1;
input  [53:0] grp_fu_1972_p_dout0;
output   grp_fu_1972_p_ce;
output  [17:0] grp_fu_1900_p_din0;
output  [34:0] grp_fu_1900_p_din1;
input  [52:0] grp_fu_1900_p_dout0;
output   grp_fu_1900_p_ce;
output  [16:0] grp_fu_1968_p_din0;
output  [34:0] grp_fu_1968_p_din1;
input  [51:0] grp_fu_1968_p_dout0;
output   grp_fu_1968_p_ce;
output  [18:0] grp_fu_2004_p_din0;
output  [34:0] grp_fu_2004_p_din1;
input  [53:0] grp_fu_2004_p_dout0;
output   grp_fu_2004_p_ce;
output  [19:0] grp_fu_1904_p_din0;
output  [34:0] grp_fu_1904_p_din1;
input  [54:0] grp_fu_1904_p_dout0;
output   grp_fu_1904_p_ce;
output  [18:0] grp_fu_2008_p_din0;
output  [34:0] grp_fu_2008_p_din1;
input  [53:0] grp_fu_2008_p_dout0;
output   grp_fu_2008_p_ce;
output  [17:0] grp_fu_1908_p_din0;
output  [34:0] grp_fu_1908_p_din1;
input  [52:0] grp_fu_1908_p_dout0;
output   grp_fu_1908_p_ce;

reg ap_idle;
reg[7:0] m_0_address0;
reg m_0_ce0;
reg[7:0] m_0_address1;
reg m_0_ce1;
reg num_V_928_out_ap_vld;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state20_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln285_reg_2133;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_state15_pp0_stage14_iter0;
wire    ap_block_pp0_stage14_subdone;
wire   [3:0] firstDense_f_V_12_0_address0;
reg    firstDense_f_V_12_0_ce0;
wire   [17:0] firstDense_f_V_12_0_q0;
wire   [3:0] firstDense_f_V_12_1_address0;
reg    firstDense_f_V_12_1_ce0;
wire   [17:0] firstDense_f_V_12_1_q0;
wire   [3:0] firstDense_f_V_12_2_address0;
reg    firstDense_f_V_12_2_ce0;
wire   [18:0] firstDense_f_V_12_2_q0;
wire   [3:0] firstDense_f_V_12_3_address0;
reg    firstDense_f_V_12_3_ce0;
wire   [18:0] firstDense_f_V_12_3_q0;
wire   [3:0] firstDense_f_V_12_4_address0;
reg    firstDense_f_V_12_4_ce0;
wire   [18:0] firstDense_f_V_12_4_q0;
wire   [3:0] firstDense_f_V_12_5_address0;
reg    firstDense_f_V_12_5_ce0;
wire   [18:0] firstDense_f_V_12_5_q0;
wire   [3:0] firstDense_f_V_12_6_address0;
reg    firstDense_f_V_12_6_ce0;
wire   [19:0] firstDense_f_V_12_6_q0;
wire   [3:0] firstDense_f_V_12_7_address0;
reg    firstDense_f_V_12_7_ce0;
wire   [18:0] firstDense_f_V_12_7_q0;
wire   [3:0] firstDense_f_V_12_8_address0;
reg    firstDense_f_V_12_8_ce0;
wire   [18:0] firstDense_f_V_12_8_q0;
wire   [3:0] firstDense_f_V_12_9_address0;
reg    firstDense_f_V_12_9_ce0;
wire   [18:0] firstDense_f_V_12_9_q0;
wire   [3:0] firstDense_f_V_12_10_address0;
reg    firstDense_f_V_12_10_ce0;
wire   [17:0] firstDense_f_V_12_10_q0;
wire   [3:0] firstDense_f_V_12_11_address0;
reg    firstDense_f_V_12_11_ce0;
wire   [16:0] firstDense_f_V_12_11_q0;
wire   [3:0] firstDense_f_V_12_12_address0;
reg    firstDense_f_V_12_12_ce0;
wire   [18:0] firstDense_f_V_12_12_q0;
wire   [3:0] firstDense_f_V_12_13_address0;
reg    firstDense_f_V_12_13_ce0;
wire   [19:0] firstDense_f_V_12_13_q0;
wire   [3:0] firstDense_f_V_12_14_address0;
reg    firstDense_f_V_12_14_ce0;
wire   [18:0] firstDense_f_V_12_14_q0;
wire   [3:0] firstDense_f_V_12_15_address0;
reg    firstDense_f_V_12_15_ce0;
wire   [17:0] firstDense_f_V_12_15_q0;
reg   [34:0] reg_484;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state17_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state18_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state19_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
wire    ap_block_pp0_stage8_11001;
reg   [34:0] reg_488;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state16_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln285_fu_505_p2;
wire   [7:0] tmp_s_fu_537_p3;
reg   [7:0] tmp_s_reg_2137;
reg   [17:0] aux2_V_reg_2255;
reg   [17:0] aux2_V_123_reg_2260;
reg   [18:0] aux2_V_124_reg_2265;
reg   [18:0] aux2_V_125_reg_2270;
reg   [18:0] aux2_V_126_reg_2275;
reg   [18:0] aux2_V_127_reg_2280;
reg   [19:0] aux2_V_128_reg_2285;
reg   [18:0] aux2_V_129_reg_2290;
reg   [18:0] aux2_V_130_reg_2295;
reg   [18:0] aux2_V_131_reg_2300;
reg   [17:0] aux2_V_132_reg_2305;
reg   [16:0] aux2_V_133_reg_2310;
reg   [18:0] aux2_V_134_reg_2315;
reg   [19:0] aux2_V_135_reg_2320;
reg   [18:0] aux2_V_136_reg_2325;
reg   [17:0] aux2_V_137_reg_2330;
wire   [52:0] zext_ln1168_fu_626_p1;
wire  signed [52:0] sext_ln1171_fu_630_p1;
wire   [52:0] zext_ln1168_93_fu_639_p1;
wire  signed [52:0] sext_ln1171_106_fu_643_p1;
reg  signed [52:0] r_V_reg_2375;
wire   [17:0] trunc_ln727_fu_680_p1;
reg   [17:0] trunc_ln727_reg_2381;
reg  signed [52:0] r_V_400_reg_2386;
wire   [17:0] trunc_ln727_134_fu_684_p1;
reg   [17:0] trunc_ln727_134_reg_2392;
wire   [53:0] zext_ln1168_94_fu_688_p1;
wire  signed [53:0] sext_ln1171_107_fu_692_p1;
wire   [53:0] zext_ln1168_95_fu_701_p1;
wire  signed [53:0] sext_ln1171_108_fu_705_p1;
wire   [35:0] num_V_250_fu_808_p2;
reg   [35:0] num_V_250_reg_2427;
wire   [0:0] r_123_fu_814_p2;
reg   [0:0] r_123_reg_2432;
reg  signed [53:0] r_V_401_reg_2437;
wire   [17:0] trunc_ln727_135_fu_819_p1;
reg   [17:0] trunc_ln727_135_reg_2443;
reg  signed [53:0] r_V_402_reg_2448;
wire   [17:0] trunc_ln727_136_fu_823_p1;
reg   [17:0] trunc_ln727_136_reg_2454;
wire   [53:0] zext_ln1168_96_fu_827_p1;
wire  signed [53:0] sext_ln1171_109_fu_831_p1;
wire   [53:0] zext_ln1168_97_fu_840_p1;
wire  signed [53:0] sext_ln1171_110_fu_844_p1;
wire   [35:0] num_V_252_fu_937_p2;
reg   [35:0] num_V_252_reg_2489;
wire   [0:0] r_124_fu_943_p2;
reg   [0:0] r_124_reg_2494;
wire   [0:0] r_125_fu_948_p2;
reg   [0:0] r_125_reg_2499;
reg  signed [53:0] r_V_403_reg_2504;
wire   [17:0] trunc_ln727_137_fu_953_p1;
reg   [17:0] trunc_ln727_137_reg_2510;
reg  signed [53:0] r_V_404_reg_2515;
wire   [17:0] trunc_ln727_138_fu_957_p1;
reg   [17:0] trunc_ln727_138_reg_2521;
wire   [54:0] zext_ln1168_98_fu_961_p1;
wire  signed [54:0] sext_ln1171_111_fu_965_p1;
wire   [53:0] zext_ln1168_99_fu_974_p1;
wire  signed [53:0] sext_ln1171_112_fu_978_p1;
wire   [35:0] num_V_254_fu_1071_p2;
reg   [35:0] num_V_254_reg_2556;
wire   [0:0] r_126_fu_1077_p2;
reg   [0:0] r_126_reg_2561;
wire   [0:0] r_127_fu_1082_p2;
reg   [0:0] r_127_reg_2566;
reg   [54:0] r_V_405_reg_2571;
wire   [17:0] trunc_ln727_139_fu_1087_p1;
reg   [17:0] trunc_ln727_139_reg_2576;
reg  signed [53:0] r_V_406_reg_2581;
wire   [17:0] trunc_ln727_140_fu_1091_p1;
reg   [17:0] trunc_ln727_140_reg_2587;
wire   [53:0] zext_ln1168_100_fu_1095_p1;
wire  signed [53:0] sext_ln1171_113_fu_1099_p1;
wire   [53:0] zext_ln1168_101_fu_1108_p1;
wire  signed [53:0] sext_ln1171_114_fu_1112_p1;
wire   [35:0] num_V_256_fu_1205_p2;
reg   [35:0] num_V_256_reg_2622;
wire   [0:0] r_128_fu_1211_p2;
reg   [0:0] r_128_reg_2627;
wire   [0:0] r_129_fu_1216_p2;
reg   [0:0] r_129_reg_2632;
reg  signed [53:0] r_V_407_reg_2637;
wire   [17:0] trunc_ln727_141_fu_1221_p1;
reg   [17:0] trunc_ln727_141_reg_2643;
reg  signed [53:0] r_V_408_reg_2648;
wire   [17:0] trunc_ln727_142_fu_1225_p1;
reg   [17:0] trunc_ln727_142_reg_2654;
wire   [52:0] zext_ln1168_102_fu_1229_p1;
wire  signed [52:0] sext_ln1171_115_fu_1233_p1;
wire   [51:0] zext_ln1168_103_fu_1242_p1;
wire  signed [51:0] sext_ln1171_116_fu_1246_p1;
wire   [35:0] num_V_258_fu_1311_p2;
reg   [35:0] num_V_258_reg_2679;
wire   [0:0] r_130_fu_1317_p2;
reg   [0:0] r_130_reg_2684;
wire   [0:0] r_131_fu_1322_p2;
reg   [0:0] r_131_reg_2689;
reg  signed [52:0] r_V_409_reg_2694;
wire   [17:0] trunc_ln727_143_fu_1327_p1;
reg   [17:0] trunc_ln727_143_reg_2700;
reg  signed [51:0] r_V_410_reg_2705;
wire   [17:0] trunc_ln727_144_fu_1331_p1;
reg   [17:0] trunc_ln727_144_reg_2711;
wire   [53:0] zext_ln1168_104_fu_1335_p1;
wire  signed [53:0] sext_ln1171_117_fu_1339_p1;
wire   [54:0] zext_ln1168_105_fu_1348_p1;
wire  signed [54:0] sext_ln1171_118_fu_1352_p1;
wire   [35:0] num_V_260_fu_1417_p2;
reg   [35:0] num_V_260_reg_2736;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state10_pp0_stage9_iter0;
wire    ap_block_pp0_stage9_11001;
wire   [0:0] r_132_fu_1423_p2;
reg   [0:0] r_132_reg_2741;
wire   [0:0] r_133_fu_1428_p2;
reg   [0:0] r_133_reg_2746;
reg  signed [53:0] r_V_411_reg_2751;
wire   [17:0] trunc_ln727_145_fu_1433_p1;
reg   [17:0] trunc_ln727_145_reg_2757;
reg   [54:0] r_V_412_reg_2762;
wire   [17:0] trunc_ln727_146_fu_1437_p1;
reg   [17:0] trunc_ln727_146_reg_2767;
wire   [53:0] zext_ln1168_106_fu_1441_p1;
wire  signed [53:0] sext_ln1171_119_fu_1445_p1;
wire   [52:0] zext_ln1168_107_fu_1454_p1;
wire  signed [52:0] sext_ln1171_120_fu_1458_p1;
wire   [35:0] num_V_262_fu_1520_p2;
reg   [35:0] num_V_262_reg_2792;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state11_pp0_stage10_iter0;
wire    ap_block_pp0_stage10_11001;
wire   [0:0] r_134_fu_1526_p2;
reg   [0:0] r_134_reg_2797;
wire   [0:0] r_135_fu_1531_p2;
reg   [0:0] r_135_reg_2802;
reg  signed [53:0] r_V_413_reg_2807;
wire   [17:0] trunc_ln727_147_fu_1536_p1;
reg   [17:0] trunc_ln727_147_reg_2813;
reg  signed [52:0] r_V_414_reg_2818;
wire   [17:0] trunc_ln727_148_fu_1540_p1;
reg   [17:0] trunc_ln727_148_reg_2824;
wire   [35:0] num_V_264_fu_1600_p2;
reg   [35:0] num_V_264_reg_2829;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_state12_pp0_stage11_iter0;
wire    ap_block_pp0_stage11_11001;
wire   [0:0] r_136_fu_1606_p2;
reg   [0:0] r_136_reg_2834;
wire   [0:0] r_137_fu_1611_p2;
reg   [0:0] r_137_reg_2839;
wire   [35:0] num_V_266_fu_1672_p2;
reg   [35:0] num_V_266_reg_2844;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_state13_pp0_stage12_iter0;
wire    ap_block_pp0_stage12_11001;
wire   [35:0] num_V_268_fu_1734_p2;
reg   [35:0] num_V_268_reg_2849;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_state14_pp0_stage13_iter0;
wire    ap_block_pp0_stage13_11001;
wire   [35:0] num_V_270_fu_1796_p2;
reg   [35:0] num_V_270_reg_2854;
wire    ap_block_pp0_stage14_11001;
wire   [35:0] num_V_272_fu_1858_p2;
reg   [35:0] num_V_272_reg_2859;
wire   [35:0] num_V_274_fu_1920_p2;
reg   [35:0] num_V_274_reg_2864;
wire   [35:0] num_V_276_fu_1979_p2;
reg   [35:0] num_V_276_reg_2869;
wire   [35:0] num_V_278_fu_2041_p2;
reg   [35:0] num_V_278_reg_2874;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln289_fu_545_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_119_fu_556_p3;
wire   [63:0] i_16_cast_fu_517_p1;
wire   [63:0] tmp_120_fu_575_p3;
wire    ap_block_pp0_stage1;
wire   [63:0] tmp_121_fu_589_p3;
wire   [63:0] tmp_122_fu_603_p3;
wire    ap_block_pp0_stage2;
wire   [63:0] tmp_123_fu_617_p3;
wire   [63:0] tmp_124_fu_657_p3;
wire    ap_block_pp0_stage3;
wire   [63:0] tmp_125_fu_671_p3;
wire   [63:0] tmp_126_fu_722_p3;
wire    ap_block_pp0_stage4;
wire   [63:0] tmp_127_fu_736_p3;
wire   [63:0] tmp_128_fu_858_p3;
wire    ap_block_pp0_stage5;
wire   [63:0] tmp_129_fu_872_p3;
wire   [63:0] tmp_130_fu_992_p3;
wire    ap_block_pp0_stage6;
wire   [63:0] tmp_131_fu_1006_p3;
wire   [63:0] tmp_132_fu_1126_p3;
wire    ap_block_pp0_stage7;
wire   [63:0] tmp_133_fu_1140_p3;
reg   [35:0] lhs_fu_124;
wire   [35:0] num_V_fu_2103_p2;
reg   [35:0] ap_sig_allocacmp_lhs_load_9;
wire    ap_loop_init;
reg   [3:0] i_fu_128;
reg   [3:0] ap_sig_allocacmp_i_10;
wire   [3:0] add_ln285_fu_511_p2;
wire    ap_block_pp0_stage4_01001;
wire   [7:0] or_ln289_fu_550_p2;
wire   [7:0] or_ln289_86_fu_570_p2;
wire   [7:0] or_ln289_87_fu_584_p2;
wire   [7:0] or_ln289_88_fu_598_p2;
wire   [7:0] or_ln289_89_fu_612_p2;
wire   [7:0] or_ln289_90_fu_652_p2;
wire   [7:0] or_ln289_91_fu_666_p2;
wire   [7:0] or_ln289_92_fu_717_p2;
wire   [7:0] or_ln289_93_fu_731_p2;
wire   [54:0] lhs_250_fu_745_p3;
wire  signed [54:0] sext_ln1245_fu_753_p1;
wire   [54:0] ret_V_fu_756_p2;
wire   [0:0] p_Result_s_fu_772_p3;
wire   [0:0] r_fu_787_p2;
wire   [0:0] or_ln412_fu_792_p2;
wire   [0:0] p_Result_407_fu_780_p3;
wire   [0:0] and_ln412_fu_798_p2;
wire   [35:0] num_V_249_fu_762_p4;
wire   [35:0] zext_ln415_fu_804_p1;
wire   [7:0] or_ln289_94_fu_853_p2;
wire   [7:0] or_ln289_95_fu_867_p2;
wire   [54:0] lhs_252_fu_881_p3;
wire  signed [54:0] sext_ln1245_72_fu_888_p1;
wire   [54:0] ret_V_121_fu_891_p2;
wire   [0:0] p_Result_378_fu_907_p3;
wire   [0:0] or_ln412_106_fu_922_p2;
wire   [0:0] p_Result_408_fu_915_p3;
wire   [0:0] and_ln412_107_fu_927_p2;
wire   [35:0] num_V_251_fu_897_p4;
wire   [35:0] zext_ln415_106_fu_933_p1;
wire   [7:0] or_ln289_96_fu_987_p2;
wire   [7:0] or_ln289_97_fu_1001_p2;
wire   [54:0] lhs_254_fu_1015_p3;
wire  signed [54:0] sext_ln1245_73_fu_1022_p1;
wire   [54:0] ret_V_122_fu_1025_p2;
wire   [0:0] p_Result_380_fu_1041_p3;
wire   [0:0] or_ln412_107_fu_1056_p2;
wire   [0:0] p_Result_409_fu_1049_p3;
wire   [0:0] and_ln412_108_fu_1061_p2;
wire   [35:0] num_V_253_fu_1031_p4;
wire   [35:0] zext_ln415_107_fu_1067_p1;
wire   [7:0] or_ln289_98_fu_1121_p2;
wire   [7:0] or_ln289_99_fu_1135_p2;
wire   [54:0] lhs_256_fu_1149_p3;
wire  signed [54:0] sext_ln1245_74_fu_1156_p1;
wire   [54:0] ret_V_123_fu_1159_p2;
wire   [0:0] p_Result_382_fu_1175_p3;
wire   [0:0] or_ln412_108_fu_1190_p2;
wire   [0:0] p_Result_410_fu_1183_p3;
wire   [0:0] and_ln412_109_fu_1195_p2;
wire   [35:0] num_V_255_fu_1165_p4;
wire   [35:0] zext_ln415_108_fu_1201_p1;
wire    ap_block_pp0_stage8;
wire   [54:0] lhs_258_fu_1255_p3;
wire  signed [54:0] sext_ln1245_75_fu_1262_p1;
wire   [54:0] ret_V_124_fu_1265_p2;
wire   [0:0] p_Result_384_fu_1281_p3;
wire   [0:0] or_ln412_109_fu_1296_p2;
wire   [0:0] p_Result_411_fu_1289_p3;
wire   [0:0] and_ln412_110_fu_1301_p2;
wire   [35:0] num_V_257_fu_1271_p4;
wire   [35:0] zext_ln415_109_fu_1307_p1;
wire    ap_block_pp0_stage9;
wire   [54:0] lhs_260_fu_1361_p3;
wire  signed [54:0] sext_ln1245_76_fu_1368_p1;
wire   [54:0] ret_V_125_fu_1371_p2;
wire   [0:0] p_Result_386_fu_1387_p3;
wire   [0:0] or_ln412_110_fu_1402_p2;
wire   [0:0] p_Result_412_fu_1395_p3;
wire   [0:0] and_ln412_111_fu_1407_p2;
wire   [35:0] num_V_259_fu_1377_p4;
wire   [35:0] zext_ln415_110_fu_1413_p1;
wire    ap_block_pp0_stage10;
wire   [54:0] lhs_262_fu_1467_p3;
wire   [54:0] ret_V_126_fu_1474_p2;
wire   [0:0] p_Result_388_fu_1489_p3;
wire   [0:0] or_ln412_111_fu_1505_p2;
wire   [0:0] p_Result_413_fu_1497_p3;
wire   [0:0] and_ln412_112_fu_1510_p2;
wire   [35:0] num_V_261_fu_1479_p4;
wire   [35:0] zext_ln415_111_fu_1516_p1;
wire    ap_block_pp0_stage11;
wire   [54:0] lhs_264_fu_1544_p3;
wire  signed [54:0] sext_ln1245_77_fu_1551_p1;
wire   [54:0] ret_V_127_fu_1554_p2;
wire   [0:0] p_Result_390_fu_1570_p3;
wire   [0:0] or_ln412_112_fu_1585_p2;
wire   [0:0] p_Result_414_fu_1578_p3;
wire   [0:0] and_ln412_113_fu_1590_p2;
wire   [35:0] num_V_263_fu_1560_p4;
wire   [35:0] zext_ln415_112_fu_1596_p1;
wire    ap_block_pp0_stage12;
wire   [54:0] lhs_266_fu_1616_p3;
wire  signed [54:0] sext_ln1245_78_fu_1623_p1;
wire   [54:0] ret_V_128_fu_1626_p2;
wire   [0:0] p_Result_392_fu_1642_p3;
wire   [0:0] or_ln412_113_fu_1657_p2;
wire   [0:0] p_Result_415_fu_1650_p3;
wire   [0:0] and_ln412_114_fu_1662_p2;
wire   [35:0] num_V_265_fu_1632_p4;
wire   [35:0] zext_ln415_113_fu_1668_p1;
wire    ap_block_pp0_stage13;
wire   [54:0] lhs_268_fu_1678_p3;
wire  signed [54:0] sext_ln1245_79_fu_1685_p1;
wire   [54:0] ret_V_129_fu_1688_p2;
wire   [0:0] p_Result_394_fu_1704_p3;
wire   [0:0] or_ln412_114_fu_1719_p2;
wire   [0:0] p_Result_416_fu_1712_p3;
wire   [0:0] and_ln412_115_fu_1724_p2;
wire   [35:0] num_V_267_fu_1694_p4;
wire   [35:0] zext_ln415_114_fu_1730_p1;
wire    ap_block_pp0_stage14;
wire   [54:0] lhs_270_fu_1740_p3;
wire  signed [54:0] sext_ln1245_80_fu_1747_p1;
wire   [54:0] ret_V_130_fu_1750_p2;
wire   [0:0] p_Result_396_fu_1766_p3;
wire   [0:0] or_ln412_115_fu_1781_p2;
wire   [0:0] p_Result_417_fu_1774_p3;
wire   [0:0] and_ln412_116_fu_1786_p2;
wire   [35:0] num_V_269_fu_1756_p4;
wire   [35:0] zext_ln415_115_fu_1792_p1;
wire   [54:0] lhs_272_fu_1802_p3;
wire  signed [54:0] sext_ln1245_81_fu_1809_p1;
wire   [54:0] ret_V_131_fu_1812_p2;
wire   [0:0] p_Result_398_fu_1828_p3;
wire   [0:0] or_ln412_116_fu_1843_p2;
wire   [0:0] p_Result_418_fu_1836_p3;
wire   [0:0] and_ln412_117_fu_1848_p2;
wire   [35:0] num_V_271_fu_1818_p4;
wire   [35:0] zext_ln415_116_fu_1854_p1;
wire   [54:0] lhs_274_fu_1864_p3;
wire  signed [54:0] sext_ln1245_82_fu_1871_p1;
wire   [54:0] ret_V_132_fu_1874_p2;
wire   [0:0] p_Result_400_fu_1890_p3;
wire   [0:0] or_ln412_117_fu_1905_p2;
wire   [0:0] p_Result_419_fu_1898_p3;
wire   [0:0] and_ln412_118_fu_1910_p2;
wire   [35:0] num_V_273_fu_1880_p4;
wire   [35:0] zext_ln415_117_fu_1916_p1;
wire   [54:0] lhs_276_fu_1926_p3;
wire   [54:0] ret_V_133_fu_1933_p2;
wire   [0:0] p_Result_402_fu_1948_p3;
wire   [0:0] or_ln412_118_fu_1964_p2;
wire   [0:0] p_Result_420_fu_1956_p3;
wire   [0:0] and_ln412_119_fu_1969_p2;
wire   [35:0] num_V_275_fu_1938_p4;
wire   [35:0] zext_ln415_118_fu_1975_p1;
wire   [54:0] lhs_278_fu_1985_p3;
wire  signed [54:0] sext_ln1245_83_fu_1992_p1;
wire   [54:0] ret_V_134_fu_1995_p2;
wire   [0:0] p_Result_404_fu_2011_p3;
wire   [0:0] or_ln412_119_fu_2026_p2;
wire   [0:0] p_Result_421_fu_2019_p3;
wire   [0:0] and_ln412_120_fu_2031_p2;
wire   [35:0] num_V_277_fu_2001_p4;
wire   [35:0] zext_ln415_119_fu_2037_p1;
wire   [54:0] lhs_280_fu_2047_p3;
wire  signed [54:0] sext_ln1245_84_fu_2054_p1;
wire   [54:0] ret_V_135_fu_2057_p2;
wire   [0:0] p_Result_406_fu_2073_p3;
wire   [0:0] or_ln412_120_fu_2088_p2;
wire   [0:0] p_Result_422_fu_2081_p3;
wire   [0:0] and_ln412_121_fu_2093_p2;
wire   [35:0] num_V_279_fu_2063_p4;
wire   [35:0] zext_ln415_120_fu_2099_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [14:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_0 #(
    .DataWidth( 18 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_0_address0),
    .ce0(firstDense_f_V_12_0_ce0),
    .q0(firstDense_f_V_12_0_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_1 #(
    .DataWidth( 18 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_1_address0),
    .ce0(firstDense_f_V_12_1_ce0),
    .q0(firstDense_f_V_12_1_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_2 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_2_address0),
    .ce0(firstDense_f_V_12_2_ce0),
    .q0(firstDense_f_V_12_2_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_3 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_3_address0),
    .ce0(firstDense_f_V_12_3_ce0),
    .q0(firstDense_f_V_12_3_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_4 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_4_address0),
    .ce0(firstDense_f_V_12_4_ce0),
    .q0(firstDense_f_V_12_4_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_5 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_5_address0),
    .ce0(firstDense_f_V_12_5_ce0),
    .q0(firstDense_f_V_12_5_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_6 #(
    .DataWidth( 20 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_6_address0),
    .ce0(firstDense_f_V_12_6_ce0),
    .q0(firstDense_f_V_12_6_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_7 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_7_address0),
    .ce0(firstDense_f_V_12_7_ce0),
    .q0(firstDense_f_V_12_7_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_8 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_8_address0),
    .ce0(firstDense_f_V_12_8_ce0),
    .q0(firstDense_f_V_12_8_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_9 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_9_address0),
    .ce0(firstDense_f_V_12_9_ce0),
    .q0(firstDense_f_V_12_9_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_10 #(
    .DataWidth( 18 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_10_address0),
    .ce0(firstDense_f_V_12_10_ce0),
    .q0(firstDense_f_V_12_10_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_11 #(
    .DataWidth( 17 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_11_address0),
    .ce0(firstDense_f_V_12_11_ce0),
    .q0(firstDense_f_V_12_11_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_12 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_12_address0),
    .ce0(firstDense_f_V_12_12_ce0),
    .q0(firstDense_f_V_12_12_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_13 #(
    .DataWidth( 20 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_13_address0),
    .ce0(firstDense_f_V_12_13_ce0),
    .q0(firstDense_f_V_12_13_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_14 #(
    .DataWidth( 19 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_14_address0),
    .ce0(firstDense_f_V_12_14_ce0),
    .q0(firstDense_f_V_12_14_q0)
);

master_fix_dense1_fix_Pipeline_Dense1_Loop216_firstDense_f_V_12_15 #(
    .DataWidth( 18 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
firstDense_f_V_12_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firstDense_f_V_12_15_address0),
    .ce0(firstDense_f_V_12_15_ce0),
    .q0(firstDense_f_V_12_15_q0)
);

master_fix_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage14_subdone) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln285_fu_505_p2 == 1'd0))) begin
            i_fu_128 <= add_ln285_fu_511_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_128 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lhs_fu_124 <= 36'd68719254338;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        lhs_fu_124 <= num_V_fu_2103_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        aux2_V_123_reg_2260 <= firstDense_f_V_12_1_q0;
        aux2_V_124_reg_2265 <= firstDense_f_V_12_2_q0;
        aux2_V_125_reg_2270 <= firstDense_f_V_12_3_q0;
        aux2_V_126_reg_2275 <= firstDense_f_V_12_4_q0;
        aux2_V_127_reg_2280 <= firstDense_f_V_12_5_q0;
        aux2_V_128_reg_2285 <= firstDense_f_V_12_6_q0;
        aux2_V_129_reg_2290 <= firstDense_f_V_12_7_q0;
        aux2_V_130_reg_2295 <= firstDense_f_V_12_8_q0;
        aux2_V_131_reg_2300 <= firstDense_f_V_12_9_q0;
        aux2_V_132_reg_2305 <= firstDense_f_V_12_10_q0;
        aux2_V_133_reg_2310 <= firstDense_f_V_12_11_q0;
        aux2_V_134_reg_2315 <= firstDense_f_V_12_12_q0;
        aux2_V_135_reg_2320 <= firstDense_f_V_12_13_q0;
        aux2_V_136_reg_2325 <= firstDense_f_V_12_14_q0;
        aux2_V_137_reg_2330 <= firstDense_f_V_12_15_q0;
        aux2_V_reg_2255 <= firstDense_f_V_12_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln285_reg_2133 <= icmp_ln285_fu_505_p2;
        num_V_272_reg_2859 <= num_V_272_fu_1858_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        num_V_250_reg_2427 <= num_V_250_fu_808_p2;
        r_123_reg_2432 <= r_123_fu_814_p2;
        r_V_401_reg_2437 <= grp_fu_1868_p_dout0;
        r_V_402_reg_2448 <= grp_fu_1876_p_dout0;
        trunc_ln727_135_reg_2443 <= trunc_ln727_135_fu_819_p1;
        trunc_ln727_136_reg_2454 <= trunc_ln727_136_fu_823_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        num_V_252_reg_2489 <= num_V_252_fu_937_p2;
        r_124_reg_2494 <= r_124_fu_943_p2;
        r_125_reg_2499 <= r_125_fu_948_p2;
        r_V_403_reg_2504 <= grp_fu_1880_p_dout0;
        r_V_404_reg_2515 <= grp_fu_1884_p_dout0;
        trunc_ln727_137_reg_2510 <= trunc_ln727_137_fu_953_p1;
        trunc_ln727_138_reg_2521 <= trunc_ln727_138_fu_957_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        num_V_254_reg_2556 <= num_V_254_fu_1071_p2;
        r_126_reg_2561 <= r_126_fu_1077_p2;
        r_127_reg_2566 <= r_127_fu_1082_p2;
        r_V_405_reg_2571 <= grp_fu_1896_p_dout0;
        r_V_406_reg_2581 <= grp_fu_1888_p_dout0;
        trunc_ln727_139_reg_2576 <= trunc_ln727_139_fu_1087_p1;
        trunc_ln727_140_reg_2587 <= trunc_ln727_140_fu_1091_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        num_V_256_reg_2622 <= num_V_256_fu_1205_p2;
        r_128_reg_2627 <= r_128_fu_1211_p2;
        r_129_reg_2632 <= r_129_fu_1216_p2;
        r_V_407_reg_2637 <= grp_fu_1916_p_dout0;
        r_V_408_reg_2648 <= grp_fu_1972_p_dout0;
        trunc_ln727_141_reg_2643 <= trunc_ln727_141_fu_1221_p1;
        trunc_ln727_142_reg_2654 <= trunc_ln727_142_fu_1225_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        num_V_258_reg_2679 <= num_V_258_fu_1311_p2;
        r_130_reg_2684 <= r_130_fu_1317_p2;
        r_131_reg_2689 <= r_131_fu_1322_p2;
        r_V_409_reg_2694 <= grp_fu_1900_p_dout0;
        r_V_410_reg_2705 <= grp_fu_1968_p_dout0;
        trunc_ln727_143_reg_2700 <= trunc_ln727_143_fu_1327_p1;
        trunc_ln727_144_reg_2711 <= trunc_ln727_144_fu_1331_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        num_V_260_reg_2736 <= num_V_260_fu_1417_p2;
        r_132_reg_2741 <= r_132_fu_1423_p2;
        r_133_reg_2746 <= r_133_fu_1428_p2;
        r_V_411_reg_2751 <= grp_fu_2004_p_dout0;
        r_V_412_reg_2762 <= grp_fu_1904_p_dout0;
        trunc_ln727_145_reg_2757 <= trunc_ln727_145_fu_1433_p1;
        trunc_ln727_146_reg_2767 <= trunc_ln727_146_fu_1437_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        num_V_262_reg_2792 <= num_V_262_fu_1520_p2;
        r_134_reg_2797 <= r_134_fu_1526_p2;
        r_135_reg_2802 <= r_135_fu_1531_p2;
        r_V_413_reg_2807 <= grp_fu_2008_p_dout0;
        r_V_414_reg_2818 <= grp_fu_1908_p_dout0;
        trunc_ln727_147_reg_2813 <= trunc_ln727_147_fu_1536_p1;
        trunc_ln727_148_reg_2824 <= trunc_ln727_148_fu_1540_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        num_V_264_reg_2829 <= num_V_264_fu_1600_p2;
        r_136_reg_2834 <= r_136_fu_1606_p2;
        r_137_reg_2839 <= r_137_fu_1611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        num_V_266_reg_2844 <= num_V_266_fu_1672_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        num_V_268_reg_2849 <= num_V_268_fu_1734_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        num_V_270_reg_2854 <= num_V_270_fu_1796_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        num_V_274_reg_2864 <= num_V_274_fu_1920_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        num_V_276_reg_2869 <= num_V_276_fu_1979_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        num_V_278_reg_2874 <= num_V_278_fu_2041_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        r_V_400_reg_2386 <= grp_fu_1892_p_dout0;
        r_V_reg_2375 <= grp_fu_1872_p_dout0;
        trunc_ln727_134_reg_2392 <= trunc_ln727_134_fu_684_p1;
        trunc_ln727_reg_2381 <= trunc_ln727_fu_680_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln285_reg_2133 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_484 <= m_0_q1;
        reg_488 <= m_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln285_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_s_reg_2137[7 : 4] <= tmp_s_fu_537_p3[7 : 4];
    end
end

always @ (*) begin
    if (((icmp_ln285_reg_2133 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage14_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_10 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_10 = i_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_sig_allocacmp_lhs_load_9 = num_V_fu_2103_p2;
    end else begin
        ap_sig_allocacmp_lhs_load_9 = lhs_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_0_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_10_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_11_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_12_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_13_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_14_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_15_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_1_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_2_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_3_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_4_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_5_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_6_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_7_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_8_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        firstDense_f_V_12_9_ce0 = 1'b1;
    end else begin
        firstDense_f_V_12_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            m_0_address0 = tmp_133_fu_1140_p3;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            m_0_address0 = tmp_131_fu_1006_p3;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            m_0_address0 = tmp_129_fu_872_p3;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            m_0_address0 = tmp_127_fu_736_p3;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            m_0_address0 = tmp_125_fu_671_p3;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            m_0_address0 = tmp_123_fu_617_p3;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            m_0_address0 = tmp_121_fu_589_p3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            m_0_address0 = tmp_119_fu_556_p3;
        end else begin
            m_0_address0 = 'bx;
        end
    end else begin
        m_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            m_0_address1 = tmp_132_fu_1126_p3;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            m_0_address1 = tmp_130_fu_992_p3;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            m_0_address1 = tmp_128_fu_858_p3;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            m_0_address1 = tmp_126_fu_722_p3;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            m_0_address1 = tmp_124_fu_657_p3;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            m_0_address1 = tmp_122_fu_603_p3;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            m_0_address1 = tmp_120_fu_575_p3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            m_0_address1 = zext_ln289_fu_545_p1;
        end else begin
            m_0_address1 = 'bx;
        end
    end else begin
        m_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_0_ce0 = 1'b1;
    end else begin
        m_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_0_ce1 = 1'b1;
    end else begin
        m_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln285_reg_2133 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        num_V_928_out_ap_vld = 1'b1;
    end else begin
        num_V_928_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln285_fu_511_p2 = (ap_sig_allocacmp_i_10 + 4'd1);

assign and_ln412_107_fu_927_p2 = (p_Result_408_fu_915_p3 & or_ln412_106_fu_922_p2);

assign and_ln412_108_fu_1061_p2 = (p_Result_409_fu_1049_p3 & or_ln412_107_fu_1056_p2);

assign and_ln412_109_fu_1195_p2 = (p_Result_410_fu_1183_p3 & or_ln412_108_fu_1190_p2);

assign and_ln412_110_fu_1301_p2 = (p_Result_411_fu_1289_p3 & or_ln412_109_fu_1296_p2);

assign and_ln412_111_fu_1407_p2 = (p_Result_412_fu_1395_p3 & or_ln412_110_fu_1402_p2);

assign and_ln412_112_fu_1510_p2 = (p_Result_413_fu_1497_p3 & or_ln412_111_fu_1505_p2);

assign and_ln412_113_fu_1590_p2 = (p_Result_414_fu_1578_p3 & or_ln412_112_fu_1585_p2);

assign and_ln412_114_fu_1662_p2 = (p_Result_415_fu_1650_p3 & or_ln412_113_fu_1657_p2);

assign and_ln412_115_fu_1724_p2 = (p_Result_416_fu_1712_p3 & or_ln412_114_fu_1719_p2);

assign and_ln412_116_fu_1786_p2 = (p_Result_417_fu_1774_p3 & or_ln412_115_fu_1781_p2);

assign and_ln412_117_fu_1848_p2 = (p_Result_418_fu_1836_p3 & or_ln412_116_fu_1843_p2);

assign and_ln412_118_fu_1910_p2 = (p_Result_419_fu_1898_p3 & or_ln412_117_fu_1905_p2);

assign and_ln412_119_fu_1969_p2 = (p_Result_420_fu_1956_p3 & or_ln412_118_fu_1964_p2);

assign and_ln412_120_fu_2031_p2 = (p_Result_421_fu_2019_p3 & or_ln412_119_fu_2026_p2);

assign and_ln412_121_fu_2093_p2 = (p_Result_422_fu_2081_p3 & or_ln412_120_fu_2088_p2);

assign and_ln412_fu_798_p2 = (p_Result_407_fu_780_p3 & or_ln412_fu_792_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage11_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage12_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage13_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage14_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign firstDense_f_V_12_0_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_10_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_11_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_12_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_13_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_14_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_15_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_1_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_2_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_3_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_4_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_5_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_6_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_7_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_8_address0 = i_16_cast_fu_517_p1;

assign firstDense_f_V_12_9_address0 = i_16_cast_fu_517_p1;

assign grp_fu_1868_p_ce = 1'b1;

assign grp_fu_1868_p_din0 = sext_ln1171_107_fu_692_p1;

assign grp_fu_1868_p_din1 = zext_ln1168_94_fu_688_p1;

assign grp_fu_1872_p_ce = 1'b1;

assign grp_fu_1872_p_din0 = sext_ln1171_fu_630_p1;

assign grp_fu_1872_p_din1 = zext_ln1168_fu_626_p1;

assign grp_fu_1876_p_ce = 1'b1;

assign grp_fu_1876_p_din0 = sext_ln1171_108_fu_705_p1;

assign grp_fu_1876_p_din1 = zext_ln1168_95_fu_701_p1;

assign grp_fu_1880_p_ce = 1'b1;

assign grp_fu_1880_p_din0 = sext_ln1171_109_fu_831_p1;

assign grp_fu_1880_p_din1 = zext_ln1168_96_fu_827_p1;

assign grp_fu_1884_p_ce = 1'b1;

assign grp_fu_1884_p_din0 = sext_ln1171_110_fu_844_p1;

assign grp_fu_1884_p_din1 = zext_ln1168_97_fu_840_p1;

assign grp_fu_1888_p_ce = 1'b1;

assign grp_fu_1888_p_din0 = sext_ln1171_112_fu_978_p1;

assign grp_fu_1888_p_din1 = zext_ln1168_99_fu_974_p1;

assign grp_fu_1892_p_ce = 1'b1;

assign grp_fu_1892_p_din0 = sext_ln1171_106_fu_643_p1;

assign grp_fu_1892_p_din1 = zext_ln1168_93_fu_639_p1;

assign grp_fu_1896_p_ce = 1'b1;

assign grp_fu_1896_p_din0 = sext_ln1171_111_fu_965_p1;

assign grp_fu_1896_p_din1 = zext_ln1168_98_fu_961_p1;

assign grp_fu_1900_p_ce = 1'b1;

assign grp_fu_1900_p_din0 = sext_ln1171_115_fu_1233_p1;

assign grp_fu_1900_p_din1 = zext_ln1168_102_fu_1229_p1;

assign grp_fu_1904_p_ce = 1'b1;

assign grp_fu_1904_p_din0 = sext_ln1171_118_fu_1352_p1;

assign grp_fu_1904_p_din1 = zext_ln1168_105_fu_1348_p1;

assign grp_fu_1908_p_ce = 1'b1;

assign grp_fu_1908_p_din0 = sext_ln1171_120_fu_1458_p1;

assign grp_fu_1908_p_din1 = zext_ln1168_107_fu_1454_p1;

assign grp_fu_1916_p_ce = 1'b1;

assign grp_fu_1916_p_din0 = sext_ln1171_113_fu_1099_p1;

assign grp_fu_1916_p_din1 = zext_ln1168_100_fu_1095_p1;

assign grp_fu_1968_p_ce = 1'b1;

assign grp_fu_1968_p_din0 = sext_ln1171_116_fu_1246_p1;

assign grp_fu_1968_p_din1 = zext_ln1168_103_fu_1242_p1;

assign grp_fu_1972_p_ce = 1'b1;

assign grp_fu_1972_p_din0 = sext_ln1171_114_fu_1112_p1;

assign grp_fu_1972_p_din1 = zext_ln1168_101_fu_1108_p1;

assign grp_fu_2004_p_ce = 1'b1;

assign grp_fu_2004_p_din0 = sext_ln1171_117_fu_1339_p1;

assign grp_fu_2004_p_din1 = zext_ln1168_104_fu_1335_p1;

assign grp_fu_2008_p_ce = 1'b1;

assign grp_fu_2008_p_din0 = sext_ln1171_119_fu_1445_p1;

assign grp_fu_2008_p_din1 = zext_ln1168_106_fu_1441_p1;

assign i_16_cast_fu_517_p1 = ap_sig_allocacmp_i_10;

assign icmp_ln285_fu_505_p2 = ((ap_sig_allocacmp_i_10 == 4'd14) ? 1'b1 : 1'b0);

assign lhs_250_fu_745_p3 = {{ap_sig_allocacmp_lhs_load_9}, {19'd0}};

assign lhs_252_fu_881_p3 = {{num_V_250_reg_2427}, {19'd0}};

assign lhs_254_fu_1015_p3 = {{num_V_252_reg_2489}, {19'd0}};

assign lhs_256_fu_1149_p3 = {{num_V_254_reg_2556}, {19'd0}};

assign lhs_258_fu_1255_p3 = {{num_V_256_reg_2622}, {19'd0}};

assign lhs_260_fu_1361_p3 = {{num_V_258_reg_2679}, {19'd0}};

assign lhs_262_fu_1467_p3 = {{num_V_260_reg_2736}, {19'd0}};

assign lhs_264_fu_1544_p3 = {{num_V_262_reg_2792}, {19'd0}};

assign lhs_266_fu_1616_p3 = {{num_V_264_reg_2829}, {19'd0}};

assign lhs_268_fu_1678_p3 = {{num_V_266_reg_2844}, {19'd0}};

assign lhs_270_fu_1740_p3 = {{num_V_268_reg_2849}, {19'd0}};

assign lhs_272_fu_1802_p3 = {{num_V_270_reg_2854}, {19'd0}};

assign lhs_274_fu_1864_p3 = {{num_V_272_reg_2859}, {19'd0}};

assign lhs_276_fu_1926_p3 = {{num_V_274_reg_2864}, {19'd0}};

assign lhs_278_fu_1985_p3 = {{num_V_276_reg_2869}, {19'd0}};

assign lhs_280_fu_2047_p3 = {{num_V_278_reg_2874}, {19'd0}};

assign num_V_249_fu_762_p4 = {{ret_V_fu_756_p2[54:19]}};

assign num_V_250_fu_808_p2 = (num_V_249_fu_762_p4 + zext_ln415_fu_804_p1);

assign num_V_251_fu_897_p4 = {{ret_V_121_fu_891_p2[54:19]}};

assign num_V_252_fu_937_p2 = (num_V_251_fu_897_p4 + zext_ln415_106_fu_933_p1);

assign num_V_253_fu_1031_p4 = {{ret_V_122_fu_1025_p2[54:19]}};

assign num_V_254_fu_1071_p2 = (num_V_253_fu_1031_p4 + zext_ln415_107_fu_1067_p1);

assign num_V_255_fu_1165_p4 = {{ret_V_123_fu_1159_p2[54:19]}};

assign num_V_256_fu_1205_p2 = (num_V_255_fu_1165_p4 + zext_ln415_108_fu_1201_p1);

assign num_V_257_fu_1271_p4 = {{ret_V_124_fu_1265_p2[54:19]}};

assign num_V_258_fu_1311_p2 = (num_V_257_fu_1271_p4 + zext_ln415_109_fu_1307_p1);

assign num_V_259_fu_1377_p4 = {{ret_V_125_fu_1371_p2[54:19]}};

assign num_V_260_fu_1417_p2 = (num_V_259_fu_1377_p4 + zext_ln415_110_fu_1413_p1);

assign num_V_261_fu_1479_p4 = {{ret_V_126_fu_1474_p2[54:19]}};

assign num_V_262_fu_1520_p2 = (num_V_261_fu_1479_p4 + zext_ln415_111_fu_1516_p1);

assign num_V_263_fu_1560_p4 = {{ret_V_127_fu_1554_p2[54:19]}};

assign num_V_264_fu_1600_p2 = (num_V_263_fu_1560_p4 + zext_ln415_112_fu_1596_p1);

assign num_V_265_fu_1632_p4 = {{ret_V_128_fu_1626_p2[54:19]}};

assign num_V_266_fu_1672_p2 = (num_V_265_fu_1632_p4 + zext_ln415_113_fu_1668_p1);

assign num_V_267_fu_1694_p4 = {{ret_V_129_fu_1688_p2[54:19]}};

assign num_V_268_fu_1734_p2 = (num_V_267_fu_1694_p4 + zext_ln415_114_fu_1730_p1);

assign num_V_269_fu_1756_p4 = {{ret_V_130_fu_1750_p2[54:19]}};

assign num_V_270_fu_1796_p2 = (num_V_269_fu_1756_p4 + zext_ln415_115_fu_1792_p1);

assign num_V_271_fu_1818_p4 = {{ret_V_131_fu_1812_p2[54:19]}};

assign num_V_272_fu_1858_p2 = (num_V_271_fu_1818_p4 + zext_ln415_116_fu_1854_p1);

assign num_V_273_fu_1880_p4 = {{ret_V_132_fu_1874_p2[54:19]}};

assign num_V_274_fu_1920_p2 = (num_V_273_fu_1880_p4 + zext_ln415_117_fu_1916_p1);

assign num_V_275_fu_1938_p4 = {{ret_V_133_fu_1933_p2[54:19]}};

assign num_V_276_fu_1979_p2 = (num_V_275_fu_1938_p4 + zext_ln415_118_fu_1975_p1);

assign num_V_277_fu_2001_p4 = {{ret_V_134_fu_1995_p2[54:19]}};

assign num_V_278_fu_2041_p2 = (num_V_277_fu_2001_p4 + zext_ln415_119_fu_2037_p1);

assign num_V_279_fu_2063_p4 = {{ret_V_135_fu_2057_p2[54:19]}};

assign num_V_928_out = lhs_fu_124;

assign num_V_fu_2103_p2 = (num_V_279_fu_2063_p4 + zext_ln415_120_fu_2099_p1);

assign or_ln289_86_fu_570_p2 = (tmp_s_reg_2137 | 8'd2);

assign or_ln289_87_fu_584_p2 = (tmp_s_reg_2137 | 8'd3);

assign or_ln289_88_fu_598_p2 = (tmp_s_reg_2137 | 8'd4);

assign or_ln289_89_fu_612_p2 = (tmp_s_reg_2137 | 8'd5);

assign or_ln289_90_fu_652_p2 = (tmp_s_reg_2137 | 8'd6);

assign or_ln289_91_fu_666_p2 = (tmp_s_reg_2137 | 8'd7);

assign or_ln289_92_fu_717_p2 = (tmp_s_reg_2137 | 8'd8);

assign or_ln289_93_fu_731_p2 = (tmp_s_reg_2137 | 8'd9);

assign or_ln289_94_fu_853_p2 = (tmp_s_reg_2137 | 8'd10);

assign or_ln289_95_fu_867_p2 = (tmp_s_reg_2137 | 8'd11);

assign or_ln289_96_fu_987_p2 = (tmp_s_reg_2137 | 8'd12);

assign or_ln289_97_fu_1001_p2 = (tmp_s_reg_2137 | 8'd13);

assign or_ln289_98_fu_1121_p2 = (tmp_s_reg_2137 | 8'd14);

assign or_ln289_99_fu_1135_p2 = (tmp_s_reg_2137 | 8'd15);

assign or_ln289_fu_550_p2 = (tmp_s_fu_537_p3 | 8'd1);

assign or_ln412_106_fu_922_p2 = (r_123_reg_2432 | p_Result_378_fu_907_p3);

assign or_ln412_107_fu_1056_p2 = (r_124_reg_2494 | p_Result_380_fu_1041_p3);

assign or_ln412_108_fu_1190_p2 = (r_125_reg_2499 | p_Result_382_fu_1175_p3);

assign or_ln412_109_fu_1296_p2 = (r_126_reg_2561 | p_Result_384_fu_1281_p3);

assign or_ln412_110_fu_1402_p2 = (r_127_reg_2566 | p_Result_386_fu_1387_p3);

assign or_ln412_111_fu_1505_p2 = (r_128_reg_2627 | p_Result_388_fu_1489_p3);

assign or_ln412_112_fu_1585_p2 = (r_129_reg_2632 | p_Result_390_fu_1570_p3);

assign or_ln412_113_fu_1657_p2 = (r_130_reg_2684 | p_Result_392_fu_1642_p3);

assign or_ln412_114_fu_1719_p2 = (r_131_reg_2689 | p_Result_394_fu_1704_p3);

assign or_ln412_115_fu_1781_p2 = (r_132_reg_2741 | p_Result_396_fu_1766_p3);

assign or_ln412_116_fu_1843_p2 = (r_133_reg_2746 | p_Result_398_fu_1828_p3);

assign or_ln412_117_fu_1905_p2 = (r_134_reg_2797 | p_Result_400_fu_1890_p3);

assign or_ln412_118_fu_1964_p2 = (r_135_reg_2802 | p_Result_402_fu_1948_p3);

assign or_ln412_119_fu_2026_p2 = (r_136_reg_2834 | p_Result_404_fu_2011_p3);

assign or_ln412_120_fu_2088_p2 = (r_137_reg_2839 | p_Result_406_fu_2073_p3);

assign or_ln412_fu_792_p2 = (r_fu_787_p2 | p_Result_s_fu_772_p3);

assign p_Result_378_fu_907_p3 = ret_V_121_fu_891_p2[32'd19];

assign p_Result_380_fu_1041_p3 = ret_V_122_fu_1025_p2[32'd19];

assign p_Result_382_fu_1175_p3 = ret_V_123_fu_1159_p2[32'd19];

assign p_Result_384_fu_1281_p3 = ret_V_124_fu_1265_p2[32'd19];

assign p_Result_386_fu_1387_p3 = ret_V_125_fu_1371_p2[32'd19];

assign p_Result_388_fu_1489_p3 = ret_V_126_fu_1474_p2[32'd19];

assign p_Result_390_fu_1570_p3 = ret_V_127_fu_1554_p2[32'd19];

assign p_Result_392_fu_1642_p3 = ret_V_128_fu_1626_p2[32'd19];

assign p_Result_394_fu_1704_p3 = ret_V_129_fu_1688_p2[32'd19];

assign p_Result_396_fu_1766_p3 = ret_V_130_fu_1750_p2[32'd19];

assign p_Result_398_fu_1828_p3 = ret_V_131_fu_1812_p2[32'd19];

assign p_Result_400_fu_1890_p3 = ret_V_132_fu_1874_p2[32'd19];

assign p_Result_402_fu_1948_p3 = ret_V_133_fu_1933_p2[32'd19];

assign p_Result_404_fu_2011_p3 = ret_V_134_fu_1995_p2[32'd19];

assign p_Result_406_fu_2073_p3 = ret_V_135_fu_2057_p2[32'd19];

assign p_Result_407_fu_780_p3 = r_V_reg_2375[32'd18];

assign p_Result_408_fu_915_p3 = r_V_400_reg_2386[32'd18];

assign p_Result_409_fu_1049_p3 = r_V_401_reg_2437[32'd18];

assign p_Result_410_fu_1183_p3 = r_V_402_reg_2448[32'd18];

assign p_Result_411_fu_1289_p3 = r_V_403_reg_2504[32'd18];

assign p_Result_412_fu_1395_p3 = r_V_404_reg_2515[32'd18];

assign p_Result_413_fu_1497_p3 = ret_V_126_fu_1474_p2[32'd18];

assign p_Result_414_fu_1578_p3 = r_V_406_reg_2581[32'd18];

assign p_Result_415_fu_1650_p3 = r_V_407_reg_2637[32'd18];

assign p_Result_416_fu_1712_p3 = r_V_408_reg_2648[32'd18];

assign p_Result_417_fu_1774_p3 = r_V_409_reg_2694[32'd18];

assign p_Result_418_fu_1836_p3 = r_V_410_reg_2705[32'd18];

assign p_Result_419_fu_1898_p3 = r_V_411_reg_2751[32'd18];

assign p_Result_420_fu_1956_p3 = ret_V_133_fu_1933_p2[32'd18];

assign p_Result_421_fu_2019_p3 = r_V_413_reg_2807[32'd18];

assign p_Result_422_fu_2081_p3 = r_V_414_reg_2818[32'd18];

assign p_Result_s_fu_772_p3 = ret_V_fu_756_p2[32'd19];

assign r_123_fu_814_p2 = ((trunc_ln727_134_reg_2392 != 18'd0) ? 1'b1 : 1'b0);

assign r_124_fu_943_p2 = ((trunc_ln727_135_reg_2443 != 18'd0) ? 1'b1 : 1'b0);

assign r_125_fu_948_p2 = ((trunc_ln727_136_reg_2454 != 18'd0) ? 1'b1 : 1'b0);

assign r_126_fu_1077_p2 = ((trunc_ln727_137_reg_2510 != 18'd0) ? 1'b1 : 1'b0);

assign r_127_fu_1082_p2 = ((trunc_ln727_138_reg_2521 != 18'd0) ? 1'b1 : 1'b0);

assign r_128_fu_1211_p2 = ((trunc_ln727_139_reg_2576 != 18'd0) ? 1'b1 : 1'b0);

assign r_129_fu_1216_p2 = ((trunc_ln727_140_reg_2587 != 18'd0) ? 1'b1 : 1'b0);

assign r_130_fu_1317_p2 = ((trunc_ln727_141_reg_2643 != 18'd0) ? 1'b1 : 1'b0);

assign r_131_fu_1322_p2 = ((trunc_ln727_142_reg_2654 != 18'd0) ? 1'b1 : 1'b0);

assign r_132_fu_1423_p2 = ((trunc_ln727_143_reg_2700 != 18'd0) ? 1'b1 : 1'b0);

assign r_133_fu_1428_p2 = ((trunc_ln727_144_reg_2711 != 18'd0) ? 1'b1 : 1'b0);

assign r_134_fu_1526_p2 = ((trunc_ln727_145_reg_2757 != 18'd0) ? 1'b1 : 1'b0);

assign r_135_fu_1531_p2 = ((trunc_ln727_146_reg_2767 != 18'd0) ? 1'b1 : 1'b0);

assign r_136_fu_1606_p2 = ((trunc_ln727_147_reg_2813 != 18'd0) ? 1'b1 : 1'b0);

assign r_137_fu_1611_p2 = ((trunc_ln727_148_reg_2824 != 18'd0) ? 1'b1 : 1'b0);

assign r_fu_787_p2 = ((trunc_ln727_reg_2381 != 18'd0) ? 1'b1 : 1'b0);

assign ret_V_121_fu_891_p2 = ($signed(lhs_252_fu_881_p3) + $signed(sext_ln1245_72_fu_888_p1));

assign ret_V_122_fu_1025_p2 = ($signed(lhs_254_fu_1015_p3) + $signed(sext_ln1245_73_fu_1022_p1));

assign ret_V_123_fu_1159_p2 = ($signed(lhs_256_fu_1149_p3) + $signed(sext_ln1245_74_fu_1156_p1));

assign ret_V_124_fu_1265_p2 = ($signed(lhs_258_fu_1255_p3) + $signed(sext_ln1245_75_fu_1262_p1));

assign ret_V_125_fu_1371_p2 = ($signed(lhs_260_fu_1361_p3) + $signed(sext_ln1245_76_fu_1368_p1));

assign ret_V_126_fu_1474_p2 = (lhs_262_fu_1467_p3 + r_V_405_reg_2571);

assign ret_V_127_fu_1554_p2 = ($signed(lhs_264_fu_1544_p3) + $signed(sext_ln1245_77_fu_1551_p1));

assign ret_V_128_fu_1626_p2 = ($signed(lhs_266_fu_1616_p3) + $signed(sext_ln1245_78_fu_1623_p1));

assign ret_V_129_fu_1688_p2 = ($signed(lhs_268_fu_1678_p3) + $signed(sext_ln1245_79_fu_1685_p1));

assign ret_V_130_fu_1750_p2 = ($signed(lhs_270_fu_1740_p3) + $signed(sext_ln1245_80_fu_1747_p1));

assign ret_V_131_fu_1812_p2 = ($signed(lhs_272_fu_1802_p3) + $signed(sext_ln1245_81_fu_1809_p1));

assign ret_V_132_fu_1874_p2 = ($signed(lhs_274_fu_1864_p3) + $signed(sext_ln1245_82_fu_1871_p1));

assign ret_V_133_fu_1933_p2 = (lhs_276_fu_1926_p3 + r_V_412_reg_2762);

assign ret_V_134_fu_1995_p2 = ($signed(lhs_278_fu_1985_p3) + $signed(sext_ln1245_83_fu_1992_p1));

assign ret_V_135_fu_2057_p2 = ($signed(lhs_280_fu_2047_p3) + $signed(sext_ln1245_84_fu_2054_p1));

assign ret_V_fu_756_p2 = ($signed(lhs_250_fu_745_p3) + $signed(sext_ln1245_fu_753_p1));

assign sext_ln1171_106_fu_643_p1 = $signed(aux2_V_123_reg_2260);

assign sext_ln1171_107_fu_692_p1 = $signed(aux2_V_124_reg_2265);

assign sext_ln1171_108_fu_705_p1 = $signed(aux2_V_125_reg_2270);

assign sext_ln1171_109_fu_831_p1 = $signed(aux2_V_126_reg_2275);

assign sext_ln1171_110_fu_844_p1 = $signed(aux2_V_127_reg_2280);

assign sext_ln1171_111_fu_965_p1 = $signed(aux2_V_128_reg_2285);

assign sext_ln1171_112_fu_978_p1 = $signed(aux2_V_129_reg_2290);

assign sext_ln1171_113_fu_1099_p1 = $signed(aux2_V_130_reg_2295);

assign sext_ln1171_114_fu_1112_p1 = $signed(aux2_V_131_reg_2300);

assign sext_ln1171_115_fu_1233_p1 = $signed(aux2_V_132_reg_2305);

assign sext_ln1171_116_fu_1246_p1 = $signed(aux2_V_133_reg_2310);

assign sext_ln1171_117_fu_1339_p1 = $signed(aux2_V_134_reg_2315);

assign sext_ln1171_118_fu_1352_p1 = $signed(aux2_V_135_reg_2320);

assign sext_ln1171_119_fu_1445_p1 = $signed(aux2_V_136_reg_2325);

assign sext_ln1171_120_fu_1458_p1 = $signed(aux2_V_137_reg_2330);

assign sext_ln1171_fu_630_p1 = $signed(aux2_V_reg_2255);

assign sext_ln1245_72_fu_888_p1 = r_V_400_reg_2386;

assign sext_ln1245_73_fu_1022_p1 = r_V_401_reg_2437;

assign sext_ln1245_74_fu_1156_p1 = r_V_402_reg_2448;

assign sext_ln1245_75_fu_1262_p1 = r_V_403_reg_2504;

assign sext_ln1245_76_fu_1368_p1 = r_V_404_reg_2515;

assign sext_ln1245_77_fu_1551_p1 = r_V_406_reg_2581;

assign sext_ln1245_78_fu_1623_p1 = r_V_407_reg_2637;

assign sext_ln1245_79_fu_1685_p1 = r_V_408_reg_2648;

assign sext_ln1245_80_fu_1747_p1 = r_V_409_reg_2694;

assign sext_ln1245_81_fu_1809_p1 = r_V_410_reg_2705;

assign sext_ln1245_82_fu_1871_p1 = r_V_411_reg_2751;

assign sext_ln1245_83_fu_1992_p1 = r_V_413_reg_2807;

assign sext_ln1245_84_fu_2054_p1 = r_V_414_reg_2818;

assign sext_ln1245_fu_753_p1 = r_V_reg_2375;

assign tmp_119_fu_556_p3 = {{56'd0}, {or_ln289_fu_550_p2}};

assign tmp_120_fu_575_p3 = {{56'd0}, {or_ln289_86_fu_570_p2}};

assign tmp_121_fu_589_p3 = {{56'd0}, {or_ln289_87_fu_584_p2}};

assign tmp_122_fu_603_p3 = {{56'd0}, {or_ln289_88_fu_598_p2}};

assign tmp_123_fu_617_p3 = {{56'd0}, {or_ln289_89_fu_612_p2}};

assign tmp_124_fu_657_p3 = {{56'd0}, {or_ln289_90_fu_652_p2}};

assign tmp_125_fu_671_p3 = {{56'd0}, {or_ln289_91_fu_666_p2}};

assign tmp_126_fu_722_p3 = {{56'd0}, {or_ln289_92_fu_717_p2}};

assign tmp_127_fu_736_p3 = {{56'd0}, {or_ln289_93_fu_731_p2}};

assign tmp_128_fu_858_p3 = {{56'd0}, {or_ln289_94_fu_853_p2}};

assign tmp_129_fu_872_p3 = {{56'd0}, {or_ln289_95_fu_867_p2}};

assign tmp_130_fu_992_p3 = {{56'd0}, {or_ln289_96_fu_987_p2}};

assign tmp_131_fu_1006_p3 = {{56'd0}, {or_ln289_97_fu_1001_p2}};

assign tmp_132_fu_1126_p3 = {{56'd0}, {or_ln289_98_fu_1121_p2}};

assign tmp_133_fu_1140_p3 = {{56'd0}, {or_ln289_99_fu_1135_p2}};

assign tmp_s_fu_537_p3 = {{ap_sig_allocacmp_i_10}, {4'd0}};

assign trunc_ln727_134_fu_684_p1 = grp_fu_1892_p_dout0[17:0];

assign trunc_ln727_135_fu_819_p1 = grp_fu_1868_p_dout0[17:0];

assign trunc_ln727_136_fu_823_p1 = grp_fu_1876_p_dout0[17:0];

assign trunc_ln727_137_fu_953_p1 = grp_fu_1880_p_dout0[17:0];

assign trunc_ln727_138_fu_957_p1 = grp_fu_1884_p_dout0[17:0];

assign trunc_ln727_139_fu_1087_p1 = grp_fu_1896_p_dout0[17:0];

assign trunc_ln727_140_fu_1091_p1 = grp_fu_1888_p_dout0[17:0];

assign trunc_ln727_141_fu_1221_p1 = grp_fu_1916_p_dout0[17:0];

assign trunc_ln727_142_fu_1225_p1 = grp_fu_1972_p_dout0[17:0];

assign trunc_ln727_143_fu_1327_p1 = grp_fu_1900_p_dout0[17:0];

assign trunc_ln727_144_fu_1331_p1 = grp_fu_1968_p_dout0[17:0];

assign trunc_ln727_145_fu_1433_p1 = grp_fu_2004_p_dout0[17:0];

assign trunc_ln727_146_fu_1437_p1 = grp_fu_1904_p_dout0[17:0];

assign trunc_ln727_147_fu_1536_p1 = grp_fu_2008_p_dout0[17:0];

assign trunc_ln727_148_fu_1540_p1 = grp_fu_1908_p_dout0[17:0];

assign trunc_ln727_fu_680_p1 = grp_fu_1872_p_dout0[17:0];

assign zext_ln1168_100_fu_1095_p1 = reg_484;

assign zext_ln1168_101_fu_1108_p1 = reg_488;

assign zext_ln1168_102_fu_1229_p1 = reg_484;

assign zext_ln1168_103_fu_1242_p1 = reg_488;

assign zext_ln1168_104_fu_1335_p1 = reg_484;

assign zext_ln1168_105_fu_1348_p1 = reg_488;

assign zext_ln1168_106_fu_1441_p1 = reg_484;

assign zext_ln1168_107_fu_1454_p1 = reg_488;

assign zext_ln1168_93_fu_639_p1 = reg_488;

assign zext_ln1168_94_fu_688_p1 = reg_484;

assign zext_ln1168_95_fu_701_p1 = reg_488;

assign zext_ln1168_96_fu_827_p1 = reg_484;

assign zext_ln1168_97_fu_840_p1 = reg_488;

assign zext_ln1168_98_fu_961_p1 = reg_484;

assign zext_ln1168_99_fu_974_p1 = reg_488;

assign zext_ln1168_fu_626_p1 = reg_484;

assign zext_ln289_fu_545_p1 = tmp_s_fu_537_p3;

assign zext_ln415_106_fu_933_p1 = and_ln412_107_fu_927_p2;

assign zext_ln415_107_fu_1067_p1 = and_ln412_108_fu_1061_p2;

assign zext_ln415_108_fu_1201_p1 = and_ln412_109_fu_1195_p2;

assign zext_ln415_109_fu_1307_p1 = and_ln412_110_fu_1301_p2;

assign zext_ln415_110_fu_1413_p1 = and_ln412_111_fu_1407_p2;

assign zext_ln415_111_fu_1516_p1 = and_ln412_112_fu_1510_p2;

assign zext_ln415_112_fu_1596_p1 = and_ln412_113_fu_1590_p2;

assign zext_ln415_113_fu_1668_p1 = and_ln412_114_fu_1662_p2;

assign zext_ln415_114_fu_1730_p1 = and_ln412_115_fu_1724_p2;

assign zext_ln415_115_fu_1792_p1 = and_ln412_116_fu_1786_p2;

assign zext_ln415_116_fu_1854_p1 = and_ln412_117_fu_1848_p2;

assign zext_ln415_117_fu_1916_p1 = and_ln412_118_fu_1910_p2;

assign zext_ln415_118_fu_1975_p1 = and_ln412_119_fu_1969_p2;

assign zext_ln415_119_fu_2037_p1 = and_ln412_120_fu_2031_p2;

assign zext_ln415_120_fu_2099_p1 = and_ln412_121_fu_2093_p2;

assign zext_ln415_fu_804_p1 = and_ln412_fu_798_p2;

always @ (posedge ap_clk) begin
    tmp_s_reg_2137[3:0] <= 4'b0000;
end

endmodule //master_fix_dense1_fix_Pipeline_Dense1_Loop216
